---
title: "Final_Patchplots"
output: html_document
date: "2026-02-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(png)

```

```{r}

#Figure 1

map_img <- readPNG("../../../Output/Paper1_OutputV2/Plots/Final_Patchplots/Map_Figure.png")


load( "../../../Output/Paper1_OutputV2/Plots/r2_barplot_pooled.RData")
load("../../../Output/Paper1_OutputV2/Plots/All_Country_Intervals.RData")

load("../../../Output/Paper1_OutputV2/Plots/conc_ride_color.RData")
load("../../../Output/Paper1_OutputV2/Plots/r2_barplot_matched.RData")


#Figure 2
load("../../../Output/Paper1_OutputV2/Plots/conc_year.RData")
load("../../../Output/Paper1_OutputV2/Plots/year_outcome_scatter.RData")
load("../../../Output/Paper1_OutputV2/Plots/mat_child_scatter.RData")
load("../../../Output/Paper1_OutputV2/Plots/vi_plot.RData")

#Figure 3
load("../../../Output/Paper1_OutputV2/Plots/R2_Barplot_ByStudy.RData")
load("../../../Output/Paper1_OutputV2/madres_plots.RData")
load("../../../Output/Paper1_OutputV2/summ_socio_ridge.RData")

```

#Figure 1


```{r}
p_pdf <- ggplot() +
  annotation_raster(map_img, xmin = -Inf, xmax = Inf,
                     ymin = -Inf, ymax = Inf) +
  theme_void()

```


```{r}
# patch <- (r2_barplot_pooled_Cohort + ggtitle("Explanatory Power by Location") + theme(legend.position = "none") + 
#             r2_barplot_matched)/ all_plot / conc_ride_color + theme(legend.position = "none")

patch <- p_pdf / all_plot / conc_ride_color + theme(legend.position = "none",
                                                    plot.title = element_text(hjust = 0)) + labs(title = "Exposure Concentrations Across Matched Strata")


pdf(file = "../../../Output/Paper1_OutputV2/Plots/Final_Patchplots/Figure1_All.pdf",height = 25,width =19)
patch + 
    plot_layout(heights = c(4, 2,2)) +
  #plot_layout(guides = "collect") +    
  plot_annotation(
  title = 'Geography as the Primary Driver of Exposomic Variation',
  #tag_levels = list(c("B", "C", "D","E"))
  tag_levels = "A")  &
  theme(plot.tag = element_text(size = 20),
        plot.title = element_text(size = 15),
        axis.text.x = element_text(size = 15)) 
dev.off()
```

#Figure 2
-----
```{r}
fig2_patch <- sum_yr / (year_outcome_scatter + mat_child_scatter) / vi_plot


fig2_patch <- fig2_patch +  
    plot_layout(heights = c(4, 2,2)) + plot_annotation(tag_levels = "A")

ggsave(fig2_patch,file = "../../../Output/Paper1_OutputV2/Plots/Final_Patchplots/Figure2_All.pdf",height = 24,width =18)

```

#Figure 3
----
```{r}
edu_plot <- madres_plots[["CCREOH__Mat_Edu"]] +
  theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_blank())+
  ggtitle("Exposome Concentration by Education")
race_plot <- madres_plots[["CCREOH__Mat_Race"]] +
    theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_blank()) +
  ggtitle("Exposome Concentration by Race/Ethnicity")

```

```{r}
design <- "
AB
CC
DD
"


pdf(file = "../../../Output/Paper1_OutputV2/Plots/Final_Patchplots/Figure3_All.pdf",height = 20,width =18)
patch <- summ_socio_ridge + r2_barplot_bystudy + edu_plot + race_plot 
patch + 
  plot_layout(design = design, heights = c(3, 1, 1)) +
  #plot_layout(guides = "collect") +    
  plot_annotation(
  title = 'Sociodemographics Help Explain Exposomic Variation',
  tag_levels = "A"
)  &
  theme(plot.tag = element_text(size = 20))
dev.off()
```

#Supp Patchplots
-----------
```{r}
load("../../../Output/Paper1_OutputV2/Plots/Demo_Patch.RData")
load("../../../Output/Paper1_OutputV2/Plots/cum_conc_plot.RData")

load("../../../Output/Paper1_OutputV2/Plots/Avg_World_Map.RData")
load( "../../../Output/Paper1_OutputV2/Plots/r2_barplot_pooled.RData")
load("../../../Output/Paper1_OutputV2/Plots/r2_barplot_matched.RData")
load("../../../Output/Paper1_OutputV2/Plots/r2_barplot_loc.RData")

load("../../../Output/Paper1_OutputV2/Plots/year_hist.RData")
load("../../../Output/Paper1_OutputV2/Plots/child_adult_mean_bar.RData")

```


```{r}
pdf(file = "../../../Output/Paper1_OutputV2/Plots/Final_Patchplots/Demo_Conc_Patch.pdf",height = 20,width =14)
patch <- demo_patch/ cum_conc 
patch + 
  plot_layout(heights = c(1,1, 4)) +
  #plot_layout(guides = "collect") +    
  plot_annotation(
  tag_levels = "A"
)  &
  theme(plot.tag = element_text(size = 20))
dev.off()

```

```{r}
pdf(file = "../../../Output/Paper1_OutputV2/Plots/Final_Patchplots/Loc_Supp_Patch.pdf",height = 14,width =16)
patch <- (average_map + r2_barplot_pooled_Cohort + ggtitle("Distributional Contribution of Location")) / (r2_barplot_matched + ggtitle("Distributional Contribution of Location") + r2_barplot_loc + ggtitle("Distributional Contribution of Location"))
patch + 
  plot_layout(heights = c(1,1,1,1)) +
  #plot_layout(guides = "collect") +    
  plot_annotation(
  tag_levels = "A"
)  &
  theme(plot.tag = element_text(size = 20))
dev.off()

```


```{r}
pdf(file = "../../../Output/Paper1_OutputV2/Plots/Final_Patchplots/Time_Supp.pdf",height = 12,width =10)
patch <- (year_hist + child_adult_mean_bar) 
patch + 
  plot_layout(heights = c(1,3)) +
  #plot_layout(guides = "collect") +    
  plot_annotation(
  tag_levels = "A"
)  &
  theme(plot.tag = element_text(size = 20))
dev.off()

```