---
title: "Quant_Reg_Results_Plots"
output: html_document
date: "2025-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
-----------
```{r}
library(tidyverse)
library(paletteer)
library(data.table)
library(ggdist)
library(ggrepel)
library(missMDA)
library(FactoMineR)
library(factoextra)
library(patchwork)
library(ggpubr)
```



```{r}
#New Classifications
#Trace elements
Trace_Elements_Theme <- unique(c("As","Ba", "Be","Cd" ,"Co","Cs","Mn", 
                  "Mo","Pb","Sb", "Tl","U", "W","Cr","Cu",
                  "Hg" ,"Ni","Pt","Sn",
                  "V","Zn", "Al", "Mg","Se"  ))


length(Trace_Elements_Theme)
#Phenols
Phenols_Theme <- unique(c("BP3","BPA","BPF","BPS","DCP24","DCP25","TCC","TCS","BUPB","ETPB","MEPB","PRPB","BP1",
                          "BP2","BP8","BPAF","BPAP","BPB","BPP","BPZ","DHB34","HB4",
                          "OH4BP","OHETP","OHMEP","PCP","TCP245","TCP246","DCP","TCP24","PHE","PHEN"))
length(Phenols_Theme)

#Polycyclic_Aromatic_hydrocarbons 
PAH_Theme <- unique(c("NAP1","NAP2","PYR1","FLUO2","PHEN1","PHEN2PHEN3","PHEN4","PHEN9","PHET","PHEN2",
                      "PHEN3","FLUO2_FLUO3","PHEN2_PHEN3","FLU","FLUO","PYR","NAP"))

length(PAH_Theme)

#Phthalates
Phthalates_Theme <- unique(c("MBZP","MCPP","MECPP","MEHHP","MEHP","MEOHP","MEP","MIBP","MNBP","MCMHP",
                             "MCHP","MCHPP","MCINP","MCIOP","MCMHP","MHXP","MINP","MIPP","MMP","MOP","MPEP",
                             "MCOCH","MHNCH","MINP","MCOP","MECPTP","MBZP","MCPP","MEHHTP","MIBP","MHPP","MBZ","MBP",
                             "MCI","MCMH","MCO","MCP","MEC","MEH","MEHH","MEO","MEOH","MHN","MIB","MIN",
                             "MNB"))

length(Phthalates_Theme)

#Parabens
Parabens_Theme <- unique(c("BUPB","ETPB","MEPB","PRPB","BZPB","HEPB","BUP","ETP","PRP"))
length(Parabens_Theme)

#Smoking/Smoking
Smoking_Theme <- unique(c("COTT","HCOTT","NICT","NNAL","COT"))
length(Smoking_Theme)

#Inflam
Inflam_Theme <- unique(c("HAPTOGLOBIN","FLT3L","TIMP1","TIMP2","IL17F","GMCSF","IFNG","IL10","MIP3A",
                         "IL12P70", "IL13","IL15","IL17A","IL22","IL9","IL1B","IL33","IL2","IL21",
                         "IL4"," IL23","IL5","IL6","IL17EIL25","IL27","IL31","TNFA","TNFB","IL28A",
                         "MMP1","MMP2","MMP7","MMP9","MMP10","CRP","LTE4","IL8","IL23"))

length(Inflam_Theme)

#Pesticide

Pesticide_Theme <- unique(c("DEP","DETP","DMDP","DMP","DMTP","PBA",
                            "TCP","DEDP","GPS","FPBA","PNP","IMPY","D24","AMPA",
                            "MDA","T245","BHCH","HCB","PPDDE","PPDDT","TCHL","TNON",
                            "OCHL","PPDDD"))

length(Pesticide_Theme)

#Volatile Organic Compounds
VOC_Theme <- unique(c("HPMA","HPMA2","SPMA","HMPMA"))

length(VOC_Theme)

#Oxidative Stress Markers
OXID_Theme <- unique(c("F2A8IP","F2A23D","F2AVI","F2A12I","OS8OHDG","OSMDA","OS8O","OSMD"))

length(OXID_Theme)

#PFAS
PFAS_Theme <- unique(c("NMFOSAA","PFBS" ,"PFDA","PFDODA" ,
                "PFDS" ,"PFHPA" ,"PFHXA" , "PFHXS" ,
                "PFNA" , "PFOA" , "PFOS","PFOSA", "PFUNDA",
                "NETFOSAA","PFPEA","ETFOSA","PFBA","PFPEA","PFHPS"))

length(PFAS_Theme)

#Flame Retardants
Flame_Retardant_Theme <- unique(c("BDE47","BDE99","BDE100","BDCPP","DPHP","TBBA",
                                  "BCETP","BCPP","DBUP","DBZP","DOCP","DPCP","BDE153",
                                  "BDE154","BDE183","BDE28","BDE47","BDE17","BDE66",
                                  "BDE85","BDE99","PBB153","BDE28","BDE85"))
length(Flame_Retardant_Theme)

PCB_Theme <- unique(c( "PCB105_PCB127","PCB110", "PCB114_PCB122","PCB118_PCB106", "PCB128", "PCB137",
  "PCB138_PCB158","PCB146_PCB161", "PCB153","PCB156","PCB157","PCB167","PCB170","PCB172_PCB192", "PCB177",
  "PCB180","PCB182_PCB187","PCB183", "PCB18_PCB17","PCB194",
  "PCB195","PCB196_PCB203", "PCB199","PCB202","PCB206","PCB208","PCB209","PCB22",
  "PCB31_PCB28", "PCB33_PCB20","PCB37","PCB41_PCB64","PCB44","PCB47_48_75",
  "PCB49_PCB43","PCB52_PCB73","PCB5_PCB8","PCB70_PCB76","PCB73_PCB95","PCB74_PCB61",
  "PCB85_PCB120","PCB90_101_89","PCB99"))

#Bisdithiocarbamates 
Bisdithiocarbamates_Theme <- unique(c("ETU","PTU"))

#Cellular adhesion molecules 
CAM_Theme <- unique(c("ICAM1","VCAM1","ESEL","PSEL"))

#Lipids

Lipids_Theme <- unique(c("CHOL","OXLDL","TG"))

#Nutrients
Nutrients_Theme <- unique(c("GAMTOC","ALPTOC","ZEAXAN","CRYPTO","LYCOPE","ALPCARO",
                            "BETCARO","RET","FOL","ADIPO"))
length(Nutrients_Theme)


Lipid_Metab <- c("LEP")

Thromboxane <- c("DHTHRM")


Other_Theme <- c(Bisdithiocarbamates_Theme,CAM_Theme,Lipids_Theme,Nutrients_Theme,Lipid_Metab,Thromboxane)
```
Input Data
------------

```{r}
 

#load("../../Output/Child_SDOH_Metab_Quantile_Results.RData")
#Reg_Results <- Child_SDOH_Metab_Quantile_Results
#load("../../Output/Final_Model_Child_SDOH_Metab_Quantile_Results_QuantData.RData")

data_files <- list.files(
  path = "../../../Output/Paper1_OutputV2/Pooled_Output",
  #pattern = "*Quantile",   # matches files that end with 'All.RData'
  recursive = FALSE,
  full.names = TRUE
)

invisible(lapply(data_files, load, .GlobalEnv))  # loads data_*_list objects into .GlobalEnv


load("../../../Input/Harmonized_Datasets/Harmonized_Targeted.RData")
load("../../../Input/Harmonized_Datasets/Harmonized_SDOH.RData")

```

```{r}
ExWAS_SDOH_Exposures <- SDOH_Data_All %>% 
  mutate(Edu_Any = case_when(!is.na(Max_Edu) ~ Max_Edu,
                             is.na(Max_Edu) ~ Mat_Edu,
                             !is.na(Mat_Edu) ~ Mat_Edu)) %>% 
  mutate(Mat_Child_Comb_Race = case_when(!is.na(Child_Race) ~ Child_Race,
                             is.na(Child_Race) ~ Mat_Race,
                             !is.na(Mat_Race) ~ Mat_Race)) %>% 
  mutate(Mat_Age = as.numeric(Mat_Age)) %>% 
  dplyr::mutate(Location = relevel(as.factor(Location),ref = "United_States")) %>% 
mutate(Location_Country = case_when(Location == "United_States"  ~ "United_States",
                                    Location == "NorthEast_US" ~ "United_States",
                                    Location == "New_Hampshire" ~ "United_States",
                                    Location == "Washington_State" ~ "United_States",
                                    Location == "Midwestern_US" ~ "United_States",
                                    Location == "Denver" ~ "United_States",
                                    Location == "Baltimore" ~ "United_States",
                                    Location == "Sacramento" ~ "United_States",
                                    Location == "Southern_California" ~ "United_States",
                                    Location == "Syracuse" ~ "United_States",
                                    Location == "Michigan" ~ "United_States",
                                    Location == "California" ~ "United_States",
                                    Location == "SanFrancisco" ~ "United_States",
                                    Location == "Massachusetts" ~ "United_States",
                                    TRUE ~ "Worldwide")) %>% 
  mutate(Mat_Edu_Binary = case_when(
  Mat_Edu %in% c("No_Education",
                 "Primary_Education",
                 "Primary_School",
                 "High_School") ~ "No_College",
  Mat_Edu %in% c("Some_College",
                 "Four_Year_College_Degree",
                 "Some_Grad_School") ~ "Some_College",
  Mat_Edu == "Not_Reported" ~ NA
)) %>% 
  mutate(Mat_Income_Binary = case_when(
  Mat_Income %in% c("0_25k", "25_49k") ~ "Under_49k",
  Mat_Income %in% c("50_74k", "75_99k", "100_124k", 
                "Over_100k", "Over_125k", "Over_49k") ~ "Over_49k",
  TRUE ~ NA
)) %>% 
  dplyr::select(Child_PID,Mat_PID,Study,Mat_Age,Mat_Race,
                Mat_Edu,Child_Sex,Child_Race,Mat_Income,
                Mat_Edu_Binary,Child_Age,Mat_Income_Binary,
                Mat_Child_Comb_Race) %>% 
  mutate(Study =  str_remove(Study, '[_]\\w+|:'))


```


Results Parse Function
-----
```{r}
Parse_Results <- function(Results_List = Child_SDOH_Metab_Quantile_Results_SexByStudy,Cohort_Meta = Cohort_Meta){
  
  
  if(Cohort_Meta == T){
    
    All_Res <- list()
  
  for(i in seq_along(Results_List)){
    
    curr_study <- Results_List[[i]]
    
             #print(i)
      
         curr_results <- try(curr_study[[1]][["Regression_Results"]] %>% 
             dplyr::filter(Variable != "(Intercept)") %>% 
             mutate(Adj_P = p.adjust(P_Value,method = "fdr"),
            Sig_10 = ifelse(Adj_P <= 0.10,1,0 ),
            Study = names(Results_List[i])) )

         if(is.character(curr_results)){
           next
         }
         
         All_Res[[i]] <- curr_results
        
  }
  Final_Res <- bind_rows(All_Res)
    
  }else{
  
  
  All_Res <- list()
  
  for(i in seq_along(Results_List)){
    
    curr_study <- Results_List[[i]]
    
    curr_study_all_res <- list() 
             #print(i)

    for(j in seq_along(curr_study)){
      
         curr_results <- try(curr_study[[j]][[1]][["Regression_Results"]] %>% 
             dplyr::filter(Variable != "(Intercept)") %>% 
             mutate(Adj_P = p.adjust(P_Value,method = "fdr"),
            Sig_10 = ifelse(Adj_P <= 0.10,1,0 ),
            Study = names(Results_List[i])) )

         if(is.character(curr_results)){
           next
         }
         
         curr_study_all_res[[j]] <- curr_results
        
      }
      
      curr_study_all_res <-  curr_study_all_res[lengths(curr_study_all_res) != 0]

    Results <- bind_rows(curr_study_all_res)
    
      All_Res[[i]] <- Results

  }
  Final_Res <- bind_rows(All_Res)
  }
  return(Final_Res)
}
```


Process Results
----------

```{r}
Process_Quant_Results <- function(Mat_Quant_Results) {
  All_Outcome_Results_Mat <- list()
  
  for (i in seq_along(Mat_Quant_Results)) {
    Curr_Reg_Results <- Mat_Quant_Results[[i]]
    Curr_Reg_Results <- Filter(is.list, Curr_Reg_Results)
    
    All_Reg_Results <- list()
    for (j in seq_along(Curr_Reg_Results)) {
      Res <- Curr_Reg_Results[[j]][[1]]
      All_Reg_Results[[j]] <- Res
    }
    
    if (length(All_Reg_Results) == 0) {
      next
    }
    
    All_Reg_Results <- bind_rows(All_Reg_Results) %>%
      filter(!str_detect(Variable, "(Intercept)")) %>%
      mutate(
        Adj_P = p.adjust(P_Value, method = "fdr"),
        Sig_10 = ifelse(Adj_P <= 0.10, 1, 0)
      )
    
    All_Outcome_Results_Mat[[i]] <- All_Reg_Results
    names(All_Outcome_Results_Mat)[i] <- unique(All_Reg_Results$Outcome)
  }
  
  All_Outcome_Results_Mat_Df <- bind_rows(All_Outcome_Results_Mat)
  return(All_Outcome_Results_Mat_Df)
}

```

```{r}

Child_Study_Results <- Process_Quant_Results(Mat_Quant_Results = Child_Study_Quantile_Results) %>% 
  mutate(Model_Type = "Study")
Child_Year_Results <- Process_Quant_Results(Mat_Quant_Results = Child_Year_Quantile_Results) %>% 
  mutate(Model_Type = "Year")
Child_Center_Results <- Process_Quant_Results(Mat_Quant_Results = Child_Center_Quantile_Results) %>% 
  mutate(Model_Type = "Center")
Child_Location_Results <- Process_Quant_Results(Mat_Quant_Results = Child_Location_Quantile_Results) %>% 
  mutate(Model_Type = "Location")
Child_Location_Region_Results <- Process_Quant_Results(Mat_Quant_Results = Child_Location_Region_Quantile_Results) %>% 
  mutate(Model_Type = "Location_Region")

Child_Location_Year_Results <- Process_Quant_Results(Mat_Quant_Results = Child_Location_Year_Quantile_Results) %>% 
  mutate(Model_Type = "Location_Year")

Child_Location_Center_Results <- Process_Quant_Results(Mat_Quant_Results = Child_Location_Center_Quantile_Results) %>% 
  mutate(Model_Type = "Location_Center")


Child_Location_Year_Results %>% 
  View

All_Child_Models <- bind_rows(Child_Study_Results,Child_Year_Results,Child_Center_Results,
                              Child_Location_Results,Child_Location_Region_Results,
                              Child_Location_Year_Results,Child_Location_Center_Results)

```

```{r}

Mat_Study_Results <- Process_Quant_Results(Mat_Quant_Results = Mat_Study_Quantile_Results) %>% 
  mutate(Model_Type = "Study")
Mat_Year_Results <- Process_Quant_Results(Mat_Quant_Results = Mat_Year_Quantile_Results) %>% 
  mutate(Model_Type = "Year")
Mat_Center_Results <- Process_Quant_Results(Mat_Quant_Results = Mat_Center_Quantile_Results) %>% 
  mutate(Model_Type = "Center")
Mat_Location_Results <- Process_Quant_Results(Mat_Quant_Results = Mat_Location_Quantile_Results) %>% 
  mutate(Model_Type = "Location")
Mat_Location_Region_Results <- Process_Quant_Results(Mat_Quant_Results = Mat_Location_Region_Quantile_Results) %>% 
  mutate(Model_Type = "Location_Region")


All_Mat_Models <- bind_rows(Mat_Study_Results,Mat_Year_Results,Mat_Center_Results,Mat_Location_Results,Mat_Location_Region_Results)

```

R2 Values 
-------

```{r}


Over3_Child <- All_Child_Models %>% 
  dplyr::filter(Model_Type == "Location") %>% 
  group_by(Outcome) %>% 
  summarise(n_unique = n_distinct(Variable)) %>% 
  dplyr::filter(n_unique >=3) %>% 
  pull(Outcome)
  
Over3_Mat <- All_Mat_Models %>% 
  dplyr::filter(Model_Type == "Location") %>% 
  group_by(Outcome) %>% 
  summarise(n_unique = n_distinct(Variable)) %>% 
  dplyr::filter(n_unique >=3) %>% 
  pull(Outcome)
```

```{r}
Child_R2_Data <- All_Child_Models %>% 
  dplyr::filter(str_detect(Outcome, paste0(Over3_Child,collapse = "|"))) %>% 
  # dplyr::filter(str_detect(Exposure,paste0(c("Mat_Age","Mat_Edu","Mat_Income", "Max_Edu",
  #                        "Child_Age","Mat_Race","Child_Race","Mat_Child_Comb_Race"),collapse = "|"))) %>% 
  mutate(plot_R2 = ifelse(pseudo_R <= 0,0,pseudo_R)) %>% 
  dplyr::filter(!is.na(Sig_10)) %>% 
  dplyr::mutate(
    w = exp(-((Tau - 0.5)^2) / (2 * 0.15^2))) %>% 
  group_by(Model_Type,Outcome) %>% 
  summarise(plot_R2 = weighted.mean(plot_R2, w, na.rm = TRUE)) %>% 
  mutate(Category = case_when(
    Outcome %in% Trace_Elements_Theme ~ "TraceElements",
    Outcome %in% Phenols_Theme ~ "Phenols",
    Outcome %in% Phthalates_Theme ~ "Phthalates",
    Outcome %in% PAH_Theme ~ "PAH",
    Outcome %in% PCB_Theme ~ "PCB",
    Outcome %in% Parabens_Theme ~ "Parabens",
    Outcome %in% Smoking_Theme ~ "Smoking",
    Outcome %in% Inflam_Theme ~ NA,
    Outcome %in% Pesticide_Theme ~ "Pesticides",
    Outcome %in% VOC_Theme ~ "VOCs",
    Outcome %in% OXID_Theme ~ NA,
    Outcome %in% Flame_Retardant_Theme ~ "FlameRetardants",
    Outcome %in% Other_Theme ~ NA,
    Outcome %in% PFAS_Theme ~ "PFAS"
  )) %>%
  dplyr::filter(!is.na(Category)) %>% 
  #dplyr::filter(Tau == 0.5) %>% 
  #dplyr::filter(Model_Type == "Single_Exposure_Study") %>% 
  #dplyr::filter(!(Demo_Var == "Study")) %>% 
  dplyr::filter(!is.na(plot_R2))%>% 
  mutate(Population = "Child")

Mat_R2_Data <- All_Mat_Models %>% 
  dplyr::filter(str_detect(Outcome, paste0(Over3_Mat,collapse = "|"))) %>% 
  # dplyr::filter(str_detect(Exposure,paste0(c("Mat_Age","Mat_Edu","Mat_Income", "Max_Edu",
  #                        "Child_Age","Mat_Race","Child_Race","Mat_Child_Comb_Race"),collapse = "|"))) %>% 
  mutate(plot_R2 = ifelse(pseudo_R <= 0,0,pseudo_R)) %>% 
  dplyr::filter(!is.na(Sig_10)) %>% 
  dplyr::mutate(
    w = exp(-((Tau - 0.5)^2) / (2 * 0.15^2))) %>% 
  group_by(Model_Type,Outcome) %>% 
  summarise(plot_R2 = weighted.mean(plot_R2, w, na.rm = TRUE)) %>% 
  mutate(Category = case_when(
    Outcome %in% Trace_Elements_Theme ~ "TraceElements",
    Outcome %in% Phenols_Theme ~ "Phenols",
    Outcome %in% Phthalates_Theme ~ "Phthalates",
    Outcome %in% PAH_Theme ~ "PAH",
    Outcome %in% PCB_Theme ~ "PCB",
    Outcome %in% Parabens_Theme ~ "Parabens",
    Outcome %in% Smoking_Theme ~ "Smoking",
    Outcome %in% Inflam_Theme ~ NA,
    Outcome %in% Pesticide_Theme ~ "Pesticides",
    Outcome %in% VOC_Theme ~ "VOCs",
    Outcome %in% OXID_Theme ~ NA,
    Outcome %in% Flame_Retardant_Theme ~ "FlameRetardants",
    Outcome %in% Other_Theme ~ NA,
    Outcome %in% PFAS_Theme ~ "PFAS"
  )) %>%
  dplyr::filter(!is.na(Category)) %>% 
  #dplyr::filter(Tau == 0.5) %>% 
  #dplyr::filter(Model_Type == "Single_Exposure_Study") %>% 
  #dplyr::filter(!(Demo_Var == "Study")) %>% 
  dplyr::filter(!is.na(plot_R2))%>% 
  mutate(Population = "Adult")
```




```{r}



All_R2_Data <- bind_rows(Child_R2_Data,Mat_R2_Data)

unique(All_R2_Data$Model_Type)
```


 


R2 Bar Plots
-----



```{r}

# --- pick a nested model sequence (order matters) ---
#model_seq <- c("Age","Race","Sex", "Age:Sex", "Age:Sex:Study")   # change as needed
model_seq <- c("Study","Location","Year","Center",
               "Location_Region","Location_Center","Location_Year")   # change as needed

# Keep only those models & compute ordering helpers


df_f <- All_R2_Data %>% 
  filter(Model_Type %in% model_seq) %>% 
  group_by( Category,Model_Type) %>% 
  #dplyr::filter(Study == "CCREOH") %>% 
  summarise(mean_R2 = mean(plot_R2, na.rm = TRUE), .groups = "drop") %>%  
  arrange(Category, match(Model_Type, model_seq)) %>%
  group_by(Category) %>%
  mutate(
    # Force baseline to 0 and ensure monotonic increase
    #mean_R2 = cummax(mean_R2),  
    total_R2 = max(mean_R2, na.rm = TRUE),
    contrib = pmax(mean_R2 - lag(mean_R2, default = 0), 0),
    component = if_else(row_number() == 1,
                        paste0("Baseline: ", Model_Type),
                        paste0("+ ", Model_Type))
  ) %>%
  ungroup() 



mypal <- paletteer_d("ggsci::springfield_simpsons")

```




```{r}

exposome_palette <- c(
  "FlameRetardants" = "#FED439FF",  # yellow
  "PAH"             = "#709AE1FF",  # blue
  "Parabens"        = "#8A9197FF",  # gray
  "PCBs"            = "#D2AF81FF",  # tan
  "Pesticide"       = "#FD7446FF",  # orange
  "PFAS"            = "#D5E4A2FF",  # light green
  "Phenols"         = "#197EC0FF",  # deep blue
  "Phthalates"      = "#F05C3BFF",  # red-orange
  "Smoking"         = "#46732EFF",  # dark green
  "TraceElements"  = "#71D0F5FF",  # light blue
  "VOC"             = "#370335FF"   # dark purple
)


pool_colors <- paletteer_d("ggsci::springfield_simpsons")

pool <-paletteer_d("ggsci::springfield_simpsons")

# The 7 levels you want to color
comp_levels <- c("Study","Location","Year","Center",
               "Location_Region","Location_Center","Location_Year")

comp_levels <- c("Year","Location")

# Name the first 7 colors by your levels
mypal <- setNames(pool[seq_along(comp_levels)], comp_levels)


comp_levels <- names(mypal)
df_plot <- df_f%>%
  mutate(
    Category  = fct_reorder(Category, total_R2),
    component = factor(Model_Type, levels = comp_levels)
  ) %>% 
  group_by(Category) %>%
  arrange(Category, component, .by_group = TRUE) %>%
  # compute stack geometry
  mutate(
    xmin = cumsum(lag(contrib, default = 0)),
    xmax = xmin + contrib,
    xmid = (xmin + xmax) / 2,
    frac = contrib / sum(contrib, na.rm = TRUE)
  ) %>%
  # flag largest slice (break ties deterministically by first factor level)
  mutate(is_max = contrib == max(contrib, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(component = factor(component, levels = names(mypal))) %>%  
  dplyr::filter(Model_Type == "Location")



totals <- df_plot %>%
  group_by(Category) %>%
  summarise(total = sum(contrib, na.rm = TRUE), .groups = "drop")


# 2) Beautiful stacked horizontal bars + total marker
r2_barplot <- ggplot(df_plot, aes(x = total_R2, y = Category, fill = Category)) +
  geom_bar(stat="identity", width=0.5) +

  # Add label only to largest bar in each Category
  # geom_text(
  #   data = df_plot %>% dplyr::filter(is_max) %>% dplyr::filter(str_detect(All_Vars,"Study")),
  #   aes(label = label_percent(accuracy = 1)(frac)),
  #   position = position_stack(vjust = 0.65),
  #   color = "black", size = 4, fontface = "bold"
  # ) +

  # Total R² dot and label
  # geom_point(
  #   data = totals, aes(x = total, y = Category),
  #   shape = 21, size = 2.8, stroke = 0.2, fill = "black", color = "black",
  #   inherit.aes = FALSE
  # ) +
  # geom_text(
  #   data = totals, aes(x = total, y = Category,
  #                      label = number(total, accuracy = 0.01)),
  #   hjust = -0.25, vjust = 0.5, size = 3.2, color = "grey15",
  #   inherit.aes = FALSE
  # ) +

  scale_fill_manual(values = exposome_palette, drop = FALSE) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0.06)),
    labels = label_number(accuracy = 0.01)
  ) +
  labs(
    #title = expression("Average Incremental " * R^2 * " by Model Term"),
    title = "Explanatory Power by Location",
    x = expression(Contribution~to~prediction~("(" * mean~R^2 * ")")),
    y = "Exposure Category",
    fill = "Model Term"
  ) +
  theme_classic(base_size = 12) +
  theme(
    plot.title      = element_text(size = 16, face = "bold", hjust = 0),
    axis.title.x    = element_text(size = 18, face = "bold"),
    axis.title.y    = element_text(size = 18, face = "bold"),
    axis.text.x     = element_text(size = 18, face = "bold"),
    axis.text.y     = element_text(size = 18),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.4),
    panel.grid.minor.x = element_blank(),
    axis.ticks.y    = element_blank(),
    legend.position = "bottom",
    legend.title    = element_text(size = 11, face = "bold"),
    legend.text     = element_text(size = 10)
  ) 


pdf(file = "../../../Output/Paper1_OutputV2/Plots/R2_Pooled_Bar.pdf",height = 6,width = 8)
print(r2_barplot)
dev.off()

r2_barplot_pooled_Cohort <- r2_barplot
save(r2_barplot_pooled_Cohort,file = "../../../Output/Paper1_OutputV2/Plots/r2_barplot_pooled.RData")

```


```{r}
All_R2_Data %>% 
  filter(Model_Type == "Location") %>% View
```


```{r}
df_plot %>% View
  group_by(All_Vars) %>% 
  summarise(mean_val = mean(mean_R2)) %>% 
  View
  
  
df_f %>% 
  dplyr::filter(Model_Type == "Year"|Model_Type == "Location") %>% 
  View

```

```{r}
df_f%>%
  mutate(
    Category  = fct_reorder(Category, total_R2),
    component = factor(Model_Type, levels = comp_levels)
  ) %>% 
  group_by(Category) %>%
  arrange(Category, component, .by_group = TRUE) %>%
  # compute stack geometry
  mutate(
    xmin = cumsum(lag(contrib, default = 0)),
    xmax = xmin + contrib,
    xmid = (xmin + xmax) / 2,
    frac = contrib / sum(contrib, na.rm = TRUE)
  ) %>%
  # flag largest slice (break ties deterministically by first factor level)
  mutate(is_max = contrib == max(contrib, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(component = factor(component, levels = names(mypal))) %>% 
  dplyr::filter(Model_Type == "Year") %>% 
  View
```


```{r}
# pdf(file = "../../../Output/Final_Paper1_Output/Plots/R2_Bar_Beta_Box.pdf",height = 6,width = 13)
# patchplot <- (beta_p + r2_barplot) 
# patchplot + plot_annotation(
#   title = 'Effect Size and R² By Exposure Category',
#   tag_levels = "A"
# )
# 
# dev.off()

```

```{r}
df_f %>% 
  mutate(
    xmin = cumsum(lag(contrib, default = 0)),
    xmax = xmin + contrib,
    xmid = (xmin + xmax) / 2,
    frac = contrib / sum(contrib, na.rm = TRUE)
  ) %>% 
  group_by(Category,All_Vars) %>% 
  summarise(mean_totalr2 = mean(mean_R2),
            mean_contrib = mean(contrib),
            mean_frac = mean(frac)) %>% 
  View
```



Manuscript Values Beta
----
```{r}


All_Beta_Data %>% 
filter(
    Model_Type == "Single_Exposure_Study",
    Demo_Var != "Study"

  ) %>%
  group_by(Demo_Var,Population) %>% 
  summarise(Cat_Demo_Beta = mean(Beta,na.rm = T)) %>% 
  View

All_Beta_Data %>% 
filter(
    Model_Type == "Single_Exposure_Study",
    Demo_Var != "Study"
  ) %>%
  group_by(Category,Population) %>% 
  summarise(Cat_Demo_Beta = round(mean(Beta,na.rm = T),3)) %>% 
  View
```

Manuscript Value R2
-----

```{r}
All_R2_Data %>% 
filter(
    Model_Type == "Single_Exposure_Study"
   # Demo_Var != "Study"

  ) %>%
  group_by(Demo_Var,Population) %>% 
  summarise(Cat_Demo_R2 = mean(plot_R2,na.rm = T)) %>% 
  View

All_R2_Data %>% 
filter(
    Model_Type == "Single_Exposure_Study",
    Demo_Var != "Study"

  ) %>%
  group_by(Category,Population) %>% 
  summarise(Cat_Demo_R2 = mean(plot_R2,na.rm = T)) %>% 
  View
```

