---
title: "Figure3Patchplot"
output: html_document
date: "2025-10-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

```{r}
load("../../../Output/Paper1_OutputV2/Plots/R2_Barplot_ByStudy.RData")
load("../../../Output/Paper1_OutputV2/madres_plots.RData")
load("../../../Output/Paper1_OutputV2/summ_socio_ridge.RData")
names(madres_plots)
```

```{r}
edu_plot <- madres_plots[["CCREOH__Mat_Edu"]] +
  theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_blank())+
  ggtitle("Exposome Concentration by Education")
race_plot <- madres_plots[["CCREOH__Mat_Race"]] +
    theme(axis.text.x = element_text(size = 16),
        axis.title.y = element_blank()) +
  ggtitle("Exposome Concentration by Race/Ethnicity")


```


```{r}
design <- "
AB
CC
DD
"


pdf(file = "../../../Output/Paper1_OutputV2/Plots/Figure5_All.pdf",height = 20,width =18)
patch <- summ_socio_ridge + r2_barplot_bystudy + edu_plot + race_plot 
patch + 
  plot_layout(design = design, heights = c(3, 1, 1)) +
  #plot_layout(guides = "collect") +    
  plot_annotation(
  title = 'Sociodemographics Help Explain Exposomic Variation',
  tag_levels = "A"
)  &
  theme(plot.tag = element_text(size = 20))
dev.off()
```



```{r}

```

