---
title: "PXS_Voter"
output: html_document
date: "2024-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
-----------
```{r}
library(tidyverse)
library(quantreg)
```


Input Data
------------

```{r}

#load("../../Input/Harmonized_Datasets/Harmonized_Outcomes.RData")
load("../../Input/Harmonized_Datasets/ZIP_SDOH_Clean.RData")
load("../../Input/Harmonized_Datasets/Harmonized_Targeted.RData")

```

```{r}

ExWAS_SDOH_Exposures <- ZIP_SDOH %>% 
  dplyr::mutate(Mat_Age = as.numeric(Mat_Age)) %>% 
  dplyr::mutate(Mat_Marital_Status = relevel(as.factor(Mat_Marital_Status), ref = "Married")) %>% 
  dplyr::mutate(Mat_Race = relevel(as.factor(Mat_Race), ref = "White")) %>% 
  dplyr::mutate(Mat_Edu = relevel(as.factor(Mat_Edu), ref = "Four_Year_College_Degree")) %>% 
  mutate(Mat_Age = as.numeric(Mat_Age)) %>% 
  mutate(Mat_Edu_Binary = case_when(
    Mat_Edu %in% c("No_Education",
                   "Primary_Education",
                   "Primary_School",
                   "High_School") ~ "No_College",
    Mat_Edu %in% c("Some_College",
                   "Four_Year_College_Degree",
                   "Some_Grad_School") ~ "Some_College",
    Mat_Edu == "Not_Reported" ~ NA
  )) %>% 
  mutate(Study = "ZIP_SDOH",
         State = toupper(State)) %>% 
  mutate(
    Country = case_when(
      Site_Location == 2 ~ "Brazil",
      Site_Location == 6 ~ "Guatemala",
      Site_Location == 7 ~ "Nicaragua",
      Site_Location == 8 ~ "Puerto Rico",
      TRUE ~ NA_character_
    )
  ) %>%  

  dplyr::mutate(Country = relevel(as.factor(Country), ref = "Guatemala"))  

```



```{r}


Mat_Data_Targeted <- Targeted_Data_All %>% 
  dplyr::filter(!is.na(Mat_PID)) %>% 
  dplyr::select(-Child_PID) %>% 
  mutate(Units = ifelse(is.na(Units),"ng/mL",Units)) %>% 
  mutate(
    Concentration = case_when(
      Units == "ug/dL" ~ Concentration * 10,
      Units == "ng/L"  ~ Concentration / 1000,
      Units == "pg/mL" ~ Concentration / 1000,
      Units == "pg/ml" ~ Concentration / 1000,
      Units == "mg/L"  ~ Concentration * 1000,
      TRUE             ~ Concentration     # keep as is if no match
    )
  ) %>% 
  dplyr::filter(!is.na(Analyte_Code)) %>% 
  group_by(Study,Mat_PID,Analyte_Code) %>% 
  summarise(Concentration = mean(Concentration,na.rm = T)) %>% 
  mutate(across(everything(), ~ replace(., is.infinite(.), 0)))
#Mat_Data_Targeted <- Targeted_Data_All %>% 
 # dplyr::filter(!is.na(Mat_PID)) %>% 
 # dplyr::select(-Child_PID) %>% 
 # dplyr::filter(!is.na(Analyte_Code)) %>% 
 # group_by(Study,Mat_PID,Analyte_Code) %>% 
 # summarise(Concentration = mean(Concentration,na.rm = T)) %>% 
 # mutate(across(everything(), ~ replace(., is.infinite(.), 0)))


myanalytes <- unique(Mat_Data_Targeted$Analyte_Code)

mat_analytes <- myanalytes

mat_list_Targeted <- list()
for(i in seq_along(myanalytes)){
  #print(i)
  curr_analyte <- myanalytes[i]
  mycols <- c("Mat_PID","Study",curr_analyte)
  
  curr_data <- Mat_Data_Targeted %>% 
    rownames_to_column("RN") %>% 
    dplyr::filter(Analyte_Code == curr_analyte) %>% 
    mutate(Study =  str_remove(Study, '[_]\\w+|:')) %>% 
    pivot_wider(names_from = Analyte_Code,values_from = Concentration) %>% 
    dplyr::select(all_of(mycols))
  
  mat_list_Targeted[[i]] <- curr_data
  names(mat_list_Targeted)[i] <- curr_analyte
  
}

```


```{r}


Mat_SDOH <- ExWAS_SDOH_Exposures %>% 
  dplyr::filter(!is.na(Mat_PID) ) %>% 
  dplyr::select(Study,Mat_PID,everything(),-Location,-Child_Age,-Pat_Edu) %>% 
mutate(
    State = str_to_upper(State),
    State = str_remove_all(State, "[^A-Z\\s]"),        # remove punctuation, numbers, brackets
    State = str_squish(State),                         # remove extra spaces
    State = case_when(
      # Puerto Rico variations
      str_detect(State, "PUERTO|P R|PR|PUETO") ~ "PUERTO RICO",
      # Suchitepequez variations
      str_detect(State, "SUCH|SUXH|SUSH|SUHI|SUCHIT|UCHITEPEQUEZ") ~ "SUCHITEPEQUEZ",
      # Bahia variations
      str_detect(State, "BAHIA|^BA$") ~ "BAHIA",
      # Guatemala
      str_detect(State, "GUATEMALA|GUTEMALA") ~ "GUATEMALA",
      # Managua variations
      str_detect(State, "MANAG") ~ "MANAGUA",
      # Alta Verapaz
      str_detect(State, "VERAPAZ") ~ "ALTA VERAPAZ",
      # Estados Unidos
      str_detect(State, "ESTADOS UNIDOS|UNITED STATES") ~ "UNITED STATES",
      # Escuintla
      str_detect(State, "ESCUINTLA") ~ "ESCUINTLA",
      # Amatitlan
      str_detect(State, "AMATITLAN") ~ "AMATITLAN",
      # Villa Nueva
      str_detect(State, "VILLA NUEVA") ~ "VILLA NUEVA",
      # Retalhuleu
      str_detect(State, "RETALHULEU") ~ "RETALHULEU",
      # State
      str_detect(State, "MAZATENANGO") ~ "MAZATENANGO",
      TRUE ~ State
    )
  )

table(Mat_SDOH$State)
```

```{r}
Quantile_Reg <- function(exp_var = NULL,
                         dataset,
                         my_outcome,
                         Reg_Type,
                         my_covariates,
                         join_var) {
  
  
  
  if(is.null(exp_var)){
    
    
    mydf_ua <- dataset %>%
      dplyr::select(all_of(c(join_var,my_outcome,my_covariates)))
    
    mydf_ua <- mydf_ua %>%
      ungroup() %>%
      dplyr::filter(complete.cases(.))
    
    if ("Study" %in% colnames(mydf_ua)) {
      
      
      
      table_n <- table(mydf_ua$Study)
      max_category <- names(table_n)[which.max(table_n)]
      
      mydf_ua <- mydf_ua %>%
        dplyr::mutate(Study = factor(Study)) %>%
        dplyr::mutate(Study = relevel(as.factor(Study), ref = max_category))
    }
    
    
    #End Loop if no data
    if(nrow(mydf_ua) == 0){
      next
    }
    
    myform <- formula(paste(my_outcome, "~",  paste0(my_covariates,collapse = "+")))
    
    #Set quantiles
    quantiles <- c(0.05,0.25, 0.5, 0.75,0.95)
    
    if ("Study" %in% colnames(mydf_ua)) {
      
      tocheck <- my_covariates[!my_covariates %in% "Study"]
      clean_df <- mydf_ua %>%
        group_by(Study) %>%
        filter(if_all(all_of(tocheck), ~ n_distinct(.) > 1)) %>%
        ungroup()
    }else{
      clean_df <- mydf_ua
    }
    
    
    #Run Quantreg
    rq_model <- rq(myform, data = clean_df, tau = quantiles)
    
    
    myform_null <- formula(paste(my_outcome, "~",  1))
    
    fit_null <- rq(myform_null, tau = quantiles, data = clean_df)
    yhat_null <- predict(fit_null)
    
    # Predict quantile values for each observation
    predicted_quantiles <- predict(rq_model, newdata = clean_df)
    predicted_quantiles <- predicted_quantiles[complete.cases(predicted_quantiles), ]
    
    yhat_full  <- predict(rq_model)        # fitted at each tau
    yhat_null  <- predict(fit_null)        # intercept-only at each tau
    
    y <- mydf_ua[[my_outcome]]
    
    
    rho_tau <- function(u, tau) u * (tau - (u < 0))
    # r1_all <- list()
    # for(z in seq_along(quantiles)){
    #
    #   numerator <- sum(rho_tau(y - predicted_quantiles, tau = quantiles[z]))
    #   denominator <- sum(rho_tau(y - yhat_null, tau = quantiles[z]))
    #
    #     # Pseudo R1
    #   r1 <- 1 - numerator / denominator
    #   r1_df <- data.frame("Tau" = quantiles[z],pseudo_R = r1)
    #   r1_all[[z]] <- r1_df
    #
    # }
    #
    # r1_all_df <- bind_rows(r1_all)
    
    r1_all_df <- purrr::map2_dfr(
      seq_along(quantiles), quantiles,
      ~{
        tau <- .y
        u_full <- y - yhat_full[, .x]
        u_null <- y - yhat_null[, .x]
        
        num <- sum(rho_tau(u_full, tau), na.rm = TRUE)
        den <- sum(rho_tau(u_null, tau), na.rm = TRUE)
        
        data.frame(Tau = tau, pseudo_R = if (den == 0) NA_real_ else 1 - num/den)
      }
    )
    
    Quantile_Results <- list(mydf_ua,predicted_quantiles)
    
    ctable_all <- try(summary(rq_model, se = "boot", R = 2,conf.int = TRUE))  # bootstrapped SEs
    
    
    #Create Regression Results
    ctable_final <- data.frame()
    for(z in seq_along(ctable_all)){
      
      curr_ctable <- ctable_all[[z]]
      ctable_df <- as.data.frame(coef(curr_ctable)) %>%
        rownames_to_column("Variable") %>%
        mutate(Tau = curr_ctable$tau,
               Outcome = my_outcome)
      
      names(ctable_df) <- c("Variable","Beta","Standard_Error","T_Value","P_Value","Tau","Outcome")
      ctable_final <- bind_rows(ctable_final,ctable_df)
    }
    conf_int_table <- broom::tidy(rq_model,conf.int = T) %>%
      dplyr::select(Lower = conf.low,Upper = conf.high)
    
    ctable_final <- bind_cols(ctable_final,conf_int_table)
    
    ctable_final <- left_join(ctable_final,r1_all_df, by ="Tau")
    
    
    Final_Results <- list(ctable_final,Quantile_Results)
    
    
    names(Final_Results) <- c("Regression_Results","Quantile_Results")
    
  }else{
    #Select Variables for model
    mydf_ua <- dataset %>%
      dplyr::select(all_of(c(join_var,my_outcome, exp_var,my_covariates))) %>%
      dplyr::filter(!is.na(!!sym(exp_var)))
    
    #End Loop if no data
    if(nrow(mydf_ua) == 0){
      next
    }
    
    
    table_n <- table(mydf_ua$Study)
    max_category <- names(table_n)[which.max(table_n)]
    
    mydf_ua <- mydf_ua %>%
      dplyr::mutate(Study = factor(Study)) %>%
      dplyr::mutate(Study = relevel(as.factor(Study),ref = max_category))
    
    #Remove low count
    if(length(unique(mydf_ua[[exp_var]])) > 10){
      
      mydf_ua <- mydf_ua[complete.cases(mydf_ua), ] %>%
        group_by(!!sym(exp_var)) %>%
        #filter(n() >= 5) %>%
        ungroup()
    }else{
      mydf_ua <- mydf_ua[complete.cases(mydf_ua), ] %>%
        group_by(!!sym(exp_var)) %>%
        filter(n() >= 5) %>%
        ungroup()
    }
    
    #End Loop if no data
    if(nrow(mydf_ua) == 0){
      next
    }
    
    
    tocheck <- exp_var[!exp_var %in% "Study"]
    clean_df <- mydf_ua %>%
      group_by(Study) %>%
      filter(if_all(all_of(tocheck), ~ n_distinct(.) > 1)) %>%
      ungroup()
    
    clean_df <- mydf_ua %>%
      group_by(Study) %>%
      filter(n_distinct(!!sym(exp_var)) > 1) %>%
      ungroup() %>%
      droplevels()
    
    
    
    n_study <- length(unique(clean_df$Study))
    
    #Adjust for study if more than one study has the information
    if(n_study == 1){
      
      myform <- formula(paste(my_outcome, "~",  exp_var))
    }else{
      
      myform <- formula(paste(my_outcome, "~",  exp_var, "+",my_covariates))
      
    }
    
    #Set quantiles
    quantiles <- c(0.05,0.25, 0.5, 0.75,0.95)
    
    
    
    
    #Run Quantreg
    rq_model <- rq(myform, data = clean_df, tau = quantiles)
    
    
    myform_null <- formula(paste(my_outcome, "~",  1))
    
    fit_null <- rq(myform_null, tau = quantiles, data = clean_df)
    yhat_null <- predict(fit_null)
    
    # Predict quantile values for each observation
    predicted_quantiles <- predict(rq_model, newdata = clean_df)
    predicted_quantiles <- predicted_quantiles[complete.cases(predicted_quantiles), ]
    
    yhat_full  <- predict(rq_model)        # fitted at each tau
    yhat_null  <- predict(fit_null)        # intercept-only at each tau
    
    y <- mydf_ua[[my_outcome]]
    
    
    rho_tau <- function(u, tau) u * (tau - (u < 0))
    # r1_all <- list()
    # for(z in seq_along(quantiles)){
    #
    #   numerator <- sum(rho_tau(y - predicted_quantiles, tau = quantiles[z]))
    #   denominator <- sum(rho_tau(y - yhat_null, tau = quantiles[z]))
    #
    #     # Pseudo R1
    #   r1 <- 1 - numerator / denominator
    #   r1_df <- data.frame("Tau" = quantiles[z],pseudo_R = r1)
    #   r1_all[[z]] <- r1_df
    #
    # }
    #
    # r1_all_df <- bind_rows(r1_all)
    
    r1_all_df <- purrr::map2_dfr(
      seq_along(quantiles), quantiles,
      ~{
        tau <- .y
        u_full <- y - yhat_full[, .x]
        u_null <- y - yhat_null[, .x]
        
        num <- sum(rho_tau(u_full, tau), na.rm = TRUE)
        den <- sum(rho_tau(u_null, tau), na.rm = TRUE)
        
        data.frame(Tau = tau, pseudo_R = if (den == 0) NA_real_ else 1 - num/den)
      }
    )
    
    
    Quantile_Results <- list(mydf_ua,predicted_quantiles)
    
    ctable_all <- try(summary(rq_model, se = "boot", R = 2,conf.int = TRUE))  # bootstrapped SEs
    
    
    
    #Create Regression Results
    ctable_final <- data.frame()
    for(z in seq_along(ctable_all)){
      
      curr_ctable <- ctable_all[[z]]
      ctable_df <- as.data.frame(coef(curr_ctable)) %>%
        rownames_to_column("Variable") %>%
        mutate(Tau = curr_ctable$tau,
               Outcome = my_outcome,
               Exposure = exp_var)
      
      names(ctable_df) <- c("Variable","Beta","Standard_Error","T_Value","P_Value","Tau","Outcome","Exposure")
      ctable_final <- bind_rows(ctable_final,ctable_df)
    }
    conf_int_table <- broom::tidy(rq_model,conf.int = T) %>%
      dplyr::select(Lower = conf.low,Upper = conf.high)
    
    ctable_final <- bind_cols(ctable_final,conf_int_table)
    
    ctable_final <- left_join(ctable_final,r1_all_df, by ="Tau")
    
    
    Final_Results <- list(ctable_final,Quantile_Results)
    
    
    names(Final_Results) <- c("Regression_Results","Quantile_Results")
    
  }
  return(Final_Results)
}

```


```{r}
ExWAS_Function_Metab <- function(Exposure_Data, myexposures,myoutcomes, Outcome_Data,mycovars,join_var,Reg_Type,curr_study){
  
  all_pheno_unadjusted <- list()
  all_pheno_adjusted <- list()
  
  #Run Regression for all outcomes
  for(j in seq_along(myoutcomes)){
    
     # pheno <- myoutcomes[97]

    pheno <- myoutcomes[j]
    adjusted_results <- list()
    unadjusted_results <- list()
    
    if(is.null(myexposures)){
      loop_n <- "CovOnly"
    }else(
      loop_n = myexposures
    )
    
    for(i in seq_along(loop_n)){
      print(i)
      my_covariates <- mycovars
      
      
      #curr_metab <- child_list_Targeted[[i]]
      # curr_pheno <- Child_Outcomes %>% 
      #   dplyr::select(Child_PID,all_of(pheno))
      
      
      curr_exposure <- Exposure_Data %>% 
        mutate(Study =  str_remove(Study, '[_]\\w+|:')) %>% 
        dplyr::select(join_var,Study,myexposures[i],all_of(my_covariates)) %>% 
        #dplyr::filter(Study == "CEHC") %>% 
        distinct()
      
      curr_pheno <- Outcome_Data[[j]] %>% 
        mutate(Study =  str_remove(Study, '[_]\\w+|:')) %>% 
        dplyr::select(join_var,Study,all_of(pheno)) %>% 
        dplyr::filter(Study == curr_study) %>% 
        dplyr::filter(!is.na(pheno))
      
      curr_outcome_pheno <- left_join(curr_pheno,curr_exposure,by = c(join_var,'Study')) %>%
        mutate(!! pheno := as.numeric(!! rlang::sym(pheno))) %>%
        distinct(.keep_all = T)
      

      if(nrow(curr_outcome_pheno) == 0){
        next
      }
      
      # curr_outcome_pheno <- left_join(curr_pheno,curr_exposure,by = c(join_var,'Study')) %>% 
      #   mutate(!! pheno := scale(as.numeric(!! rlang::sym(pheno)))) %>% 
      #   distinct(.keep_all = T)
      
      
      
      #  curr_outcome_pheno <- curr_outcome_pheno
      
      
      curr_exp <- myexposures[i]
      
      
      
      #             in_silence(
      # {
      
      Curr_Unadjusted_Results <- try(Quantile_Reg(exp_var = curr_exp,
                                                  dataset = curr_outcome_pheno,
                                                  my_outcome = pheno,
                                                  Reg_Type = Reg_Type,
                                                  my_covariates = my_covariates,
                                                  join_var = join_var))
      
      unadjusted_results[[i]] <- Curr_Unadjusted_Results
      
      names(unadjusted_results)[i] <- curr_exp
      
      #})
    }
    
    
    #filtered_unadjusted_list <- lapply(unadjusted_results, function(df) if (nrow(df) >= 2) df else NULL)
    
    
    #unadjusted_df <- bind_rows(filtered_unadjusted_list)
    
    
    
    
    all_pheno_unadjusted[[j]] <- unadjusted_results
    
    names(all_pheno_unadjusted)[j] <- myoutcomes[j]
    
  }
  
  
  return(all_pheno_unadjusted)
  
  
}

```

```{r}
suppress_all_output <- function(expr) {
  temp_file <- tempfile()
  con <- file(temp_file, open = "wt")
  
  # Redirect stdout and messages
  sink(con)
  sink(con, type = "message")
  
  # Suppress warnings and messages globally
  old_warn <- getOption("warn")
  options(warn = -1)
  
  # Evaluate expression quietly
  result <- suppressWarnings(
    suppressMessages(
      tryCatch(
        eval(expr),
        error = function(e) NULL  # suppress error output
      )
    )
  )
  
  # Restore options and sinks
  options(warn = old_warn)
  sink(NULL)
  sink(NULL, type = "message")
  close(con)
  
  invisible(result)
}



```

```{r}
Run_ExWAS_By_Study <- function(to_keep, child_sdoh, mystudies,join_var,analytes_touse,targeted_list ) {
  All_Study_Single_Exp_Results <- list()
  
  for (i in seq_along(mystudies)) {
    print(i)
    curr_sdoh <- child_sdoh %>%
      dplyr::filter(Study == mystudies[[i]]) %>%
      dplyr::select_if(~ !all(is.na(.))) %>%
      dplyr::select(where(~ n_distinct(.) > 1), Study) %>%
      dplyr::mutate(Study = stringr::str_remove(Study, '[_]\\w+|:'))
    
    # keep only the specified social exposures
    #curr_social_exps <- names(curr_sdoh)[-1]
   # curr_social_exps <- curr_social_exps[curr_social_exps %in% to_keep]
    curr_social_exps <- to_keep

    curr_study <- unique(curr_sdoh$Study)
    #curr_study <- unique(curr_sdoh %>% pull(Study))
    
    # run the Quantile ExWAS
    Curr_Results <- try(ExWAS_Function_Metab(
        Exposure_Data = curr_sdoh,
        Outcome_Data = targeted_list,
        myexposures = NULL,
        myoutcomes = analytes_touse,
        mycovars = curr_social_exps,
        join_var = join_var,
        Reg_Type = "Quantile",
        curr_study = curr_study
      ))
    
    Final_Res <- Curr_Results[lapply(Curr_Results, length) > 0]
    All_Study_Single_Exp_Results[[i]] <- Final_Res
    names(All_Study_Single_Exp_Results)[i] <- curr_study
  }
  
  # filter to non-empty results
  By_Study_AllSDOH_Child <- All_Study_Single_Exp_Results[
    lapply(All_Study_Single_Exp_Results, length) > 0
  ]
  is_char <- sapply(By_Study_AllSDOH_Child, is.character)

  # Remove character elements
  By_Study_AllSDOH_Child <- By_Study_AllSDOH_Child[!is_char]

  
  return(By_Study_AllSDOH_Child)
}
```




Run Analysis Mat
----


```{r}
mystudies <- unique(Mat_SDOH$Study)
#mat_analytes <-  c("DEDP", "DEP" , "DETP", "DMDP", "DMP" , "DMTP", "PBA" , "PNP" , "TCP" , "FPBA")
All_Study_Single_Exp_Results <- list()
for(i in seq_along(mystudies)){
  
  curr_sdoh <- Mat_SDOH %>% 
    dplyr::filter(Study == mystudies[[i]]) %>% 
    select_if(~ !all(is.na(.))) %>% 
    select(where(~n_distinct(.) > 1),Study) %>% 
    mutate(Study =  str_remove(Study, '[_]\\w+|:')) 
  
  tokeep <- c("Mat_Age","Site_Location" ,"Mat_Smoking" ,"Country" ,"Mat_Marital_Status", "Mat_Race" ,"Mat_Edu" , "Mat_Edu_Binary","State")    
  curr_social_exps <- names(curr_sdoh)[-1]
  curr_social_exps <- curr_social_exps[curr_social_exps %in% tokeep]
  curr_study <- unique(curr_sdoh$Study)
  #Run Quantile ExWAS
  Curr_Results <- suppress_all_output(quote(ExWAS_Function_Metab(Exposure_Data = curr_sdoh,
                                                                 Outcome_Data = mat_list_Targeted,
                                                                 myexposures = curr_social_exps,
                                                                 myoutcomes = mat_analytes,mycovars = "Study",join_var = "Mat_PID",
                                                                 Reg_Type = "Quantile",
                                                                 curr_study = curr_study)))
  
  Final_Res <- Curr_Results[lapply(Curr_Results, length) > 0]
  All_Study_Single_Exp_Results[[i]] <- Final_Res
  names(All_Study_Single_Exp_Results)[i] <- curr_study
  
}




#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
Zip_Single_Exp <- All_Study_Single_Exp_Results[lapply(All_Study_Single_Exp_Results, length) > 0]

save(Zip_Single_Exp, file = "../../Output/Final_Paper1_Output/Zip_Single_Exp.RData")



```

```{r}

check_singular <- function(df, cols) {
  X <- model.matrix(~ . , data = df[cols])
  qrX <- qr(X)
  rankX <- qrX$rank
  ncolX <- ncol(X)
  
  tibble(
    columns_checked = paste(cols, collapse = ", "),
    full_rank = rankX == ncolX,
    rank = rankX,
    ncol = ncolX,
    singular = rankX < ncolX
  )
}

check_singular(Mat_SDOH,tokeep)

mystudies <- unique(Mat_SDOH$Study)

All_Study_Single_Exp_Results <- list()
for(i in seq_along(mystudies)){
  
  curr_sdoh <- Mat_SDOH %>% 
    dplyr::filter(Study == mystudies[[i]]) %>% 
    select_if(~ !all(is.na(.))) %>% 
    select(where(~n_distinct(.) > 1),Study) %>% 
    mutate(Study =  str_remove(Study, '[_]\\w+|:')) 
  
  tokeep <- c("Mat_Age"  ,"Country" ,"Mat_Marital_Status", "Mat_Race" ,"Mat_Edu")    
  curr_social_exps <- names(curr_sdoh)[-1]
  curr_social_exps <- curr_social_exps[curr_social_exps %in% tokeep]
  curr_study <- unique(curr_sdoh$Study)
  #Run Quantile ExWAS
  Curr_Results <- suppress_all_output(quote(ExWAS_Function_Metab(Exposure_Data = curr_sdoh,
                                                                                      Outcome_Data = mat_list_Targeted,
                                                                                      myexposures = NULL,
                                                                                      myoutcomes = mat_analytes,
                                                                                      mycovars = curr_social_exps,
                                                                                      join_var = "Mat_PID",
                                                                                      Reg_Type = "Quantile",
                                                                                      curr_study = curr_study)))

  Final_Res <- Curr_Results[lapply(Curr_Results, length) > 0]
  All_Study_Single_Exp_Results[[i]] <- Final_Res
  names(All_Study_Single_Exp_Results)[i] <- curr_study
  
  }




#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
Zip_Full_Model <- All_Study_Single_Exp_Results[lapply(All_Study_Single_Exp_Results, length) > 0]

save(Zip_Full_Model, file = "../../Output/Final_Paper1_Output/Zip_Full_Model.RData")


```

```{r}

#Age   Race

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","Mat_Race")

By_Study_AgeRace_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_Race <- By_Study_AgeRace_Mat[lapply(By_Study_AgeRace_Mat, length) > 0]

save(ZIP_Age_Race, file = "../../Output/Final_Paper1_Output/ZIP_Age_Race.RData")


```

```{r}

#Age   Edu

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","Mat_Edu")

By_Study_AgeEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_Edu <- By_Study_AgeEdu_Mat[lapply(By_Study_AgeEdu_Mat, length) > 0]

save(ZIP_Age_Edu, file = "../../Output/Final_Paper1_Output/ZIP_Age_Edu.RData")


```

```{r}

#Age   Race Edu

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","Mat_Race","Mat_Edu")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_Edu_Race <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_Edu_Race, file = "../../Output/Final_Paper1_Output/ZIP_Age_Edu_Race.RData")


```

```{r}

#Age   Race Edu
#tokeep <- c("Mat_Age","Site_Location" ,"Mat_Smoking" ,"Country" ,"Mat_Marital_Status", "Mat_Race" ,"Mat_Edu" , "Mat_Edu_Binary","State")    

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","Mat_Race","Mat_Edu","Country")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_Edu_Race_Country <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_Edu_Race_Country, file = "../../Output/Final_Paper1_Output/ZIP_Age_Edu_Race_Country.RData")


```

```{r}

#Age   Race Edu
#tokeep <- c("Mat_Age","Site_Location" ,"Mat_Smoking" ,"Country" ,"Mat_Marital_Status", "Mat_Race" ,"Mat_Edu" , "Mat_Edu_Binary","State")    

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","Country")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_Country <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_Country, file = "../../Output/Final_Paper1_Output/ZIP_Age_Country.RData")


```

```{r}

#Age   Race Edu
#tokeep <- c("Mat_Age","Site_Location" ,"Mat_Smoking" ,"Country" ,"Mat_Marital_Status", "Mat_Race" ,"Mat_Edu" , "Mat_Edu_Binary","State")    

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","Country","Mat_Race")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_Country_Race <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_Country_Race, file = "../../Output/Final_Paper1_Output/ZIP_Age_Country_Race.RData")


```

```{r}

#Age   Race Edu
#tokeep <- c("Mat_Age","Site_Location" ,"Mat_Smoking" ,"Country" ,"Mat_Marital_Status", "Mat_Race" ,"Mat_Edu" , "Mat_Edu_Binary","State")    

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","Country","Mat_Edu")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_Country_Edu <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_Country_Edu, file = "../../Output/Final_Paper1_Output/ZIP_Age_Country_Edu.RData")


```


```{r}

#Age   Race Edu
#tokeep <- c("Mat_Age","Site_Location" ,"Mat_Smoking" ,"Country" ,"Mat_Marital_Status", "Mat_Race" ,"Mat_Edu" , "Mat_Edu_Binary","State")    

mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","State")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_State <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_State, file = "../../Output/Final_Paper1_Output/ZIP_Age_State.RData")


```

```{r}
mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","State","Mat_Race")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_State_Race <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_State_Race, file = "../../Output/Final_Paper1_Output/ZIP_Age_State_Race.RData")


```

```{r}
mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","State","Mat_Edu")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_State_Edu <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_State_Edu, file = "../../Output/Final_Paper1_Output/ZIP_Age_State_Edu.RData")


```

```{r}
mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","State","Mat_Edu","Mat_Race")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_State_Edu_Race <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_State_Edu_Race, file = "../../Output/Final_Paper1_Output/ZIP_Age_State_Edu_Race.RData")


```

```{r}
mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","State","Mat_Edu","Mat_Race","Site_Location")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_State_Edu_Race_Site <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_State_Edu_Race_Site, file = "../../Output/Final_Paper1_Output/ZIP_Age_State_Edu_Race_Site.RData")


```

```{r}
mystudies <- unique(Mat_SDOH$Study)
to_keep <- c("Mat_Age","State","Site_Location")

By_Study_AgeRaceEdu_Mat<- suppress_all_output(quote( Run_ExWAS_By_Study(
  to_keep = to_keep,
  child_sdoh = Mat_SDOH,
  mystudies = mystudies,
  join_var = "Mat_PID",
  analytes_touse = mat_analytes,
  targeted_list = mat_list_Targeted
)))


#Child_All_Exposure_Quantile_Results <- Child_SDOH_Metab_Quantile_Results
ZIP_Age_State_Site <- By_Study_AgeRaceEdu_Mat[lapply(By_Study_AgeRaceEdu_Mat, length) > 0]

save(ZIP_Age_State_Site, file = "../../Output/Final_Paper1_Output/ZIP_Age_State_Site.RData")


```

```{r}

```

