---
title: "Quant_Reg_Results_Plots"
output: html_document
date: "2025-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
-----------
```{r}
library(tidyverse)
library(paletteer)
library(data.table)
library(ggdist)
library(ggrepel)
library(missMDA)
library(FactoMineR)
library(factoextra)
library(patchwork)
library(ggpubr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

```



```{r}

#Pesticide

Pesticide_Theme <- unique(c("DEP","DETP","DMDP","DMP","DMTP","PBA",
                            "TCP","DEDP","GPS","FPBA","PNP","IMPY","D24","AMPA",
                            "MDA","T245","BHCH","HCB","PPDDE","PPDDT","TCHL","TNON",
                            "OCHL","PPDDD"))

```
Input Data
------------

```{r}
 

load("../../../Input/Harmonized_Datasets/Harmonized_Targeted.RData")
load("../../../Input/Harmonized_Datasets/ZIP_SDOH_Clean.RData")

load("../../../Output/Final_Paper1_Output/Zip_Single_Exp.RData")
load("../../../Output/Final_Paper1_Output/Zip_Full_Model.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_Country.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_Country_Edu.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_Country_Race.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_Edu.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_Edu_Race.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_Edu_Race_Country.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_Race.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_State.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_State_Edu.RData")
load("../../../Output/Final_Paper1_Output/ZIP_Age_State_Race.RData")

```

```{r}
ExWAS_SDOH_Exposures <- ZIP_SDOH %>% 
  dplyr::mutate(Mat_Age = as.numeric(Mat_Age)) %>% 
  dplyr::mutate(Mat_Marital_Status = relevel(as.factor(Mat_Marital_Status), ref = "Married")) %>% 
  dplyr::mutate(Mat_Race = relevel(as.factor(Mat_Race), ref = "White")) %>% 
  dplyr::mutate(Mat_Edu = relevel(as.factor(Mat_Edu), ref = "Four_Year_College_Degree")) %>% 
  mutate(Mat_Age = as.numeric(Mat_Age)) %>% 
  mutate(Mat_Edu_Binary = case_when(
    Mat_Edu %in% c("No_Education",
                   "Primary_Education",
                   "Primary_School",
                   "High_School") ~ "No_College",
    Mat_Edu %in% c("Some_College",
                   "Four_Year_College_Degree",
                   "Some_Grad_School") ~ "Some_College",
    Mat_Edu == "Not_Reported" ~ NA
  )) %>% 
  mutate(Study = "ZIP_SDOH",
         State = toupper(State)) %>% 
    dplyr::filter(!is.na(Mat_PID) ) %>% 
  dplyr::select(Study,Mat_PID,everything(),-Location,-Child_Age,-Pat_Edu) %>% 
mutate(
    State = str_to_upper(State),
    State = str_remove_all(State, "[^A-Z\\s]"),        # remove punctuation, numbers, brackets
    State = str_squish(State),                         # remove extra spaces
    State = case_when(
      # Puerto Rico variations
      str_detect(State, "PUERTO|P R|PR|PUETO") ~ "PUERTO RICO",
      # Suchitepequez variations
      str_detect(State, "SUCH|SUXH|SUSH|SUHI|SUCHIT|UCHITEPEQUEZ") ~ "SUCHITEPEQUEZ",
      # Bahia variations
      str_detect(State, "BAHIA|^BA$") ~ "BAHIA",
      # Guatemala
      str_detect(State, "GUATEMALA|GUTEMALA") ~ "GUATEMALA",
      # Managua variations
      str_detect(State, "MANAG") ~ "MANAGUA",
      # Alta Verapaz
      str_detect(State, "VERAPAZ") ~ "ALTA VERAPAZ",
      # Estados Unidos
      str_detect(State, "ESTADOS UNIDOS|UNITED STATES") ~ "UNITED STATES",
      # Escuintla
      str_detect(State, "ESCUINTLA") ~ "ESCUINTLA",
      # Amatitlan
      str_detect(State, "AMATITLAN") ~ "AMATITLAN",
      # Villa Nueva
      str_detect(State, "VILLA NUEVA") ~ "VILLA NUEVA",
      # Retalhuleu
      str_detect(State, "RETALHULEU") ~ "RETALHULEU",
      # State
      str_detect(State, "MAZATENANGO") ~ "MAZATENANGO",
      TRUE ~ State
    )
  )%>% 
  mutate(
    Country = case_when(
      Site_Location == 2 ~ "Brazil",
      Site_Location == 6 ~ "Guatemala",
      Site_Location == 7 ~ "Nicaragua",
      Site_Location == 8 ~ "Puerto Rico",
      TRUE ~ NA_character_
    )
  ) %>% 
  dplyr::mutate(Country = relevel(as.factor(Country), ref = "Guatemala"))   %>% 
      dplyr::mutate(Mat_Smoking = as.factor(Mat_Smoking))


table(ExWAS_SDOH_Exposures$Country)
```


Results Parse Function
-----
```{r}
Parse_Results <- function(Results_List = Child_SDOH_Metab_Quantile_Results_SexByStudy,Cohort_Meta = Cohort_Meta){
  
  
  if(Cohort_Meta == T){
    
    All_Res <- list()
  
  for(i in seq_along(Results_List)){
    
    curr_study <- Results_List[[i]]
    
             #print(i)
      
         curr_results <- try(curr_study[[1]][["Regression_Results"]] %>% 
             dplyr::filter(Variable != "(Intercept)") %>% 
             mutate(Adj_P = p.adjust(P_Value,method = "fdr"),
            Sig_10 = ifelse(Adj_P <= 0.10,1,0 ),
            Study = names(Results_List[i])) )

         if(is.character(curr_results)){
           next
         }
         
         All_Res[[i]] <- curr_results
        
  }
  Final_Res <- bind_rows(All_Res)
    
  }else{
  
  
  All_Res <- list()
  
  for(i in seq_along(Results_List)){
    
    curr_study <- Results_List[[i]]
    
    curr_study_all_res <- list() 
             #print(i)

    for(j in seq_along(curr_study)){
      
         curr_results <- try(curr_study[[j]][[1]][["Regression_Results"]] %>% 
             dplyr::filter(Variable != "(Intercept)") %>% 
             mutate(Adj_P = p.adjust(P_Value,method = "fdr"),
            Sig_10 = ifelse(Adj_P <= 0.10,1,0 ),
            Study = names(Results_List[i])) )

         if(is.character(curr_results)){
           next
         }
         
         curr_study_all_res[[j]] <- curr_results
        
      }
      
      curr_study_all_res <-  curr_study_all_res[lengths(curr_study_all_res) != 0]

    Results <- bind_rows(curr_study_all_res)
    
      All_Res[[i]] <- Results

  }
  Final_Res <- bind_rows(All_Res)
  }
  return(Final_Res)
}
```


Process Results
----------

```{r}
Process_Quant_Results <- function(Mat_Quant_Results) {
  All_Outcome_Results_Mat <- list()
  
  for (i in seq_along(Mat_Quant_Results)) {
    Curr_Reg_Results <- Mat_Quant_Results[[i]]
    Curr_Reg_Results <- Filter(is.list, Curr_Reg_Results)
    
    All_Reg_Results <- list()
    for (j in seq_along(Curr_Reg_Results)) {
      Res <- Curr_Reg_Results[[j]][[1]]
      All_Reg_Results[[j]] <- Res
    }
    
    if (length(All_Reg_Results) == 0) {
      next
    }
    
    All_Reg_Results <- bind_rows(All_Reg_Results) %>%
      filter(!str_detect(Variable, "(Intercept)")) %>%
      mutate(
        Adj_P = p.adjust(P_Value, method = "fdr"),
        Sig_10 = ifelse(Adj_P <= 0.10, 1, 0)
      )
    
    All_Outcome_Results_Mat[[i]] <- All_Reg_Results
    names(All_Outcome_Results_Mat)[i] <- unique(All_Reg_Results$Outcome)
  }
  
  All_Outcome_Results_Mat_Df <- bind_rows(All_Outcome_Results_Mat)
  return(All_Outcome_Results_Mat_Df)
}

```

```{r}
make_results_bystudy <- function(results_list,Model_Type,Population) {
  all_results <- lapply(seq_along(results_list), function(i) {
    curr_study <- names(results_list)[i]
    Process_Quant_Results(Mat_Quant_Results = results_list[[i]]) %>%
      mutate(
        Model_Type = Model_Type,
        Study = curr_study,
        Population = Population
      )
  })
  
  bind_rows(all_results)
}

```

```{r}
Single_Exp <- make_results_bystudy(results_list = Zip_Single_Exp,
                                             Model_Type = "Single_Exposure_Study",Population = "Adults")

Full_Model <- make_results_bystudy(results_list = Zip_Full_Model,
                                             Model_Type = "Full_Model",Population = "Adults")

Age_Edu <- make_results_bystudy(results_list = ZIP_Age_Edu,
                                             Model_Type = "Age_Edu",Population = "Adults")

Age_Race <- make_results_bystudy(results_list = ZIP_Age_Race,
                                             Model_Type = "Age_Race",Population = "Adults")

Age_Country <- make_results_bystudy(results_list = ZIP_Age_Country,
                                             Model_Type = "Age_Country",Population = "Adults")

Age_Edu_Race_Country <- make_results_bystudy(results_list = ZIP_Age_Edu_Race_Country,
                                             Model_Type = "Age_Edu_Race_Country",Population = "Adults")


Age_Edu_Country <- make_results_bystudy(results_list = ZIP_Age_Country,
                                             Model_Type = "Age_Edu_Race_Country",Population = "Adults")

Age_Race_Country <- make_results_bystudy(results_list = ZIP_Age_Country_Race,
                                             Model_Type = "Age_Race_Country",Population = "Adults")

Age_State <- make_results_bystudy(results_list = ZIP_Age_State,
                                             Model_Type = "Age_State",Population = "Adults")

Age_State_Edu <- make_results_bystudy(results_list = ZIP_Age_State_Edu,
                                             Model_Type = "Age_State_Edu",Population = "Adults")

Age_State_Race <- make_results_bystudy(results_list = ZIP_Age_State_Race,
                                             Model_Type = "Age_State_Race",Population = "Adults")

```


```{r}

Zip_Res <- bind_rows(Single_Exp,Full_Model,Age_Edu,Age_Race,Age_Country,
                     Age_Edu_Race_Country,Age_Edu_Country,Age_Race_Country,Age_State,
                     Age_State_Edu,Age_State_Race)

```





Plots
-------


```{r}

All_R2_Data <- Zip_Res %>% 
  # dplyr::filter(str_detect(Exposure,paste0(c("Mat_Age","Mat_Edu","Mat_Income", "Max_Edu",
  #                        "Child_Age","Mat_Race","Child_Race","Mat_Child_Comb_Race"),collapse = "|"))) %>% 
  #dplyr::filter(!Exposure %in% c("Mat_Child_Comb_Race")) %>% 
  mutate(plot_R2 = ifelse(pseudo_R <= 0,0,pseudo_R)) %>% 
  mutate(Category = "Pesticides") %>%
  dplyr::filter(!is.na(Sig_10)) %>% 
  dplyr::filter(!is.na(Category)) %>% 
  dplyr::filter(Tau == 0.5) %>% 
  mutate(Demo_Var = case_when(
    str_detect(Variable, "Study") ~ "Study",
    str_detect(Variable, "Race") ~ "Race",
    str_detect(Variable, "Sex") ~ "Sex",
    str_detect(Variable, "Income") ~ "Income",
    str_detect(Variable, "Age") ~ "Age",
    str_detect(Variable, "Edu") ~ "Education",
    str_detect(Variable, "Location") ~ "Location",
    str_detect(Variable, "State") ~ "State",
    str_detect(Variable, "Country") ~ "Country",
    TRUE ~ "Other"  # fallback value if none match
  )) %>% 
  dplyr::filter(!is.na(plot_R2)) 
```

```{r}
sum(All_R2_Data$Sig_10)

All_R2_Data %>% 
  dplyr::filter(Sig_10==1) %>% 
  View
```





```{r}

Single_Exp_Data <- All_R2_Data %>% 
  dplyr::filter(Model_Type == "Single_Exposure_Study") %>% 
  mutate(Model_Type = Demo_Var,
         All_Vars = Model_Type) %>% 
  dplyr::select(Outcome,Tau,Study,Population,Model_Type,Category,pseudo_R,All_Vars) %>% 
  mutate(plot_R2 = ifelse(pseudo_R <= 0,0,pseudo_R)) %>% 
  dplyr::filter(All_Vars == "Age")


Full_Model_R2 <- All_R2_Data %>% 
  dplyr::filter(Model_Type != "Single_Exposure_Study") %>% 
  group_by(Outcome,Tau,Study,Population,Model_Type,Category,pseudo_R) %>% 
  summarise(All_Vars = paste(unique(Demo_Var), collapse = ":")) %>% 
  mutate(plot_R2 = ifelse(pseudo_R <= 0,0,pseudo_R))

vars <- c(
  "Age", "Sex", "Race", "Income",
  "Sex:Age", "Location", "Race:Age", "Education",
  "Income:Race", "Age:Race:Sex", "Age:Education", "Age:Sex:Income",
  "Age:Sex:Education", "Sex:Education:Age", "Education:Race:Age",
  "Age:Race:Sex:Income", "Sex:Income:Race:Age", "Age:Race:Sex:Education",
  "Race:Sex:Education:Age", "Sex:Education:Race:Age",
  "Education:Income:Race:Age", "Age:Race:Sex:Education:Income",
  "Sex:Education:Income:Race:Age"
)

# Normalize order of variable names within each string
vars_normalized <- sapply(vars, function(x) {
  paste(sort(strsplit(x, ":")[[1]]), collapse = ":")
})

# Check results
#data.frame(original = vars, normalized = vars_normalized)

Full_Model_R2 <- Full_Model_R2 %>%
  mutate(All_Vars = sapply(All_Vars, function(x) paste(sort(strsplit(x, ":")[[1]]), collapse = ":")))

```




```{r}

ALl_R2 <- bind_rows(Full_Model_R2,Single_Exp_Data) 

# unique(ALl_R2$Model_Type)
# model_seq <- unique(ALl_R2$Model_Type)
# element_lengths <- nchar(model_seq)
# 
# sorted_indices <- order(element_lengths)

# Sort the original vector using these indices
#model_seq <- model_seq[sorted_indices]

# model_seq <- c("Age","Age_Edu","Age_Race", "Age_State","Age_State_Edu","Age_State_Race" ,
#                 "Age_Edu_Race_Country" )
model_seq <- c("Age","Age_Edu","Age_Race", "Age_Country","Age_Country_Edu","Age_Country_Race" ,
                "Age_Edu_Race_Country" )
df_f <- ALl_R2 %>% 
  #group_by(Outcome,Tau,Population,Model_Type,Category,pseudo_R) %>% 
  #summarise(All_Vars = paste(unique(Demo_Var), collapse = ":")) %>% 
  mutate(plot_R2 = ifelse(pseudo_R <= 0,0,pseudo_R)) %>% 
  dplyr::filter(Tau == 0.50) %>%  
  dplyr::filter(Model_Type %in% model_seq) %>% 
  filter(Model_Type %in% model_seq) %>% 
  group_by(Outcome, Model_Type) %>% 
  #dplyr::filter(Study == "CCREOH") %>% 
  summarise(mean_R2 =round(mean(plot_R2, na.rm = TRUE),3), .groups = "drop") %>%  
  arrange(Outcome, match(Model_Type, model_seq)) %>%
  group_by(Outcome) %>%
  mutate(
    # Force baseline to 0 and ensure monotonic increase
    #mean_R2 = cummax(mean_R2),  
    total_R2 = max(mean_R2, na.rm = TRUE),
    contrib = pmax(mean_R2 - lag(mean_R2, default = 0), 0),
    component = if_else(row_number() == 1,
                        paste0("Baseline: ", Model_Type),
                        paste0("+ ", Model_Type))
  ) %>%
 # dplyr::filter(!str_detect(Model_Type,"Country")) %>% 
  ungroup() 

pool <- c(
  "#FED439FF", "#709AE1FF", "#8A9197FF", "#D2AF81FF",
  "#FD7446FF", "#D5E4A2FF", "#197EC0FF", "#F05C3BFF",
  "#46732EFF", "#71D0F5FF", "#370335FF", "#075149FF",
  "#C80813FF", "#91331FFF", "#1A9993FF", "#FD8CC1FF"
)

comp_levels <- c("Age","Age_Edu","Age_Race", "Age_Country","Age_Country_Edu","Age_Country_Race" ,
                "Age_Edu_Race_Country" )

mypal <- setNames(pool[seq_along(comp_levels)], comp_levels)

#mypal <-paletteer_d("ggsci::default_igv")
comp_levels <- names(mypal)
df_plot <- df_f%>%
  mutate(
    Outcome  = fct_reorder(Outcome, total_R2),
    component = factor(Model_Type, levels = comp_levels)
  ) %>% 
  group_by(Outcome) %>%
  arrange(Outcome, component, .by_group = TRUE) %>%
  # compute stack geometry
  mutate(
    xmin = cumsum(lag(contrib, default = 0)),
    xmax = xmin + contrib,
    xmid = (xmin + xmax) / 2,
    frac = contrib / sum(contrib, na.rm = TRUE)
  ) %>%
  # flag largest slice (break ties deterministically by first factor level)
  mutate(is_max = contrib == max(contrib, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(component = factor(component, levels = names(mypal))) 

totals <- df_plot %>%
  group_by(Outcome) %>%
  summarise(total = sum(contrib, na.rm = TRUE), .groups = "drop")

r2_barplot <- ggplot(df_plot, aes(x = contrib, y = Outcome, fill = component)) +
  geom_col(width = 0.7, color = "white", linewidth = 0.2) +

  # Add label only to largest bar in each Category
  geom_text(
    data = df_plot %>% dplyr::filter(is_max) %>% dplyr::filter(str_detect(Model_Type,"Country")),
    aes(label = label_percent(accuracy = 1)(frac)),
    position = position_stack(vjust = 0.5),
    color = "black", size = 3, fontface = "bold"
  ) +

  scale_fill_manual(values = mypal, drop = FALSE) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0.06)),
    labels = label_number(accuracy = 0.01)
  ) +
  labs(
    #title = expression("Average Incremental " * R^2 * " by Model Term"),
    title = "Average Demogrpahic Explanatory Power by Model",
    x = expression(Contribution~to~prediction~("(" * mean~R^2 * ")")),
    y = "Exposure",
    fill = "Model term"
  ) +
  theme_classic(base_size = 12) +
  theme(
    plot.title      = element_text(size = 16, face = "bold", hjust = 0),
    axis.title.x    = element_text(size = 18, face = "bold"),
    axis.title.y    = element_text(size = 16, face = "bold"),
    axis.text.x     = element_text(size = 18, face = "bold"),
    axis.text.y     = element_text(size = 18),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.4),
    panel.grid.minor.x = element_blank(),
    axis.ticks.y    = element_blank(),
    legend.position = "bottom",
    legend.title    = element_text(size = 11, face = "bold"),
    legend.text     = element_text(size = 10)
  ) +
  coord_cartesian(xlim = c(0, max(totals$total, na.rm = TRUE) * 1.12))


print(r2_barplot)
r2_barplot_zip <- r2_barplot
save(r2_barplot_zip, file = "../../../Output/Final_Paper1_Output/r2_barplot_zip.RData")
```



Make Zip Intervals 
-------------
```{r}
Ref_Vars <- c("Mat_Age")
Mat_Quant_Results <- Zip_Single_Exp[[1]]
#names(Mat_Quant_Results[[1]])[names(Mat_Quant_Results[[1]]) %>% str_detect(.,paste0(Ref_Vars,collapse = "|"))]
Final_Intervals_Mat <- list()
for(j in seq_along(Mat_Quant_Results)){
#print(j)
  Curr_Quant <- Mat_Quant_Results[[j]][c(Ref_Vars)]
  Curr_Quant <- Filter(is.list, Curr_Quant)

  All_Weighted_Averages <- list()
  for(i in seq_along(Curr_Quant)){
    #print(i)
    #Select quantiles
    Quant_Data <- Curr_Quant[[i]][[2]][[1]]
    Tau_Data <- Curr_Quant[[i]][[2]][[2]] %>% as.data.frame(.)
    
    names(Tau_Data) <- c("Tau05","Tau25","Tau50","Tau75","Tau95")
    
  # All_Data <- bind_cols(Quant_Data,Tau_Data) 
  
   #Take a weighted average of quantile calculated from social exposures which creates the intervals
   weighted_averages <- numeric()
    for (col_name in c("Tau05","Tau25","Tau50","Tau75","Tau95")) {
          value_counts <- table(Tau_Data[[col_name]])
          values <- as.numeric(names(value_counts))
          weights <- as.numeric(value_counts)
          
          weighted_avg <- sum(values * weights) / sum(weights)
          
          weighted_averages[col_name] <- weighted_avg
      }
    All_Weighted_Averages[[i]] <- weighted_averages
   names(All_Weighted_Averages)[i] <- names(Curr_Quant[i])
   W_Avg_Df <- bind_rows(All_Weighted_Averages) 
   
   column_means <- sapply(W_Avg_Df[, c("Tau05","Tau25","Tau50","Tau75","Tau95")], mean, na.rm = TRUE) %>%
     t(.) %>% 
     as.data.frame(.) %>% 
     mutate(Outcome = names(Mat_Quant_Results)[j] ) %>% 
     dplyr::select(Outcome,everything())

   Final_Intervals_Mat[[j]] <- column_means
   names(Final_Intervals_Mat)[j] <- names(Mat_Quant_Results)[j]
   
   }


}

```

```{r}
ZIP_Intervals <- bind_rows(Final_Intervals_Mat) %>%
    mutate(across(where(is.numeric), ~ round(., 3)))%>% 
  mutate(IQR = Tau75 - Tau25) %>% 
  mutate(Max_Min = Tau95 - Tau05) %>% 
  mutate(Category ="Pesticides") %>% 
  dplyr::filter(!is.na(Category)) %>% 
  mutate(
      IQR_unadj = IQR,
      IQR = ifelse(IQR >= 20, 20, IQR),
      Max_Min_unadj = Max_Min,
      Max_Min = ifelse(Max_Min >= 50, 50, Max_Min),
      Flag = as.factor(ifelse(IQR >= 20, 1, 0))
    ) %>% 
  filter(!is.na(Category)) %>% 
    mutate(Max_Min_Log = log10(Max_Min + 1),
           IQR_Log = log10(IQR+ 1)) 

```

```{r}
Mat_Data_Targeted <- Targeted_Data_All %>% 
  dplyr::filter(!is.na(Mat_PID)) %>% 
  dplyr::select(-Child_PID) %>% 
  mutate(Units = ifelse(is.na(Units),"ng/mL",Units)) %>% 
  mutate(
    Concentration = case_when(
      Units == "ug/dL" ~ Concentration * 10,
      Units == "ng/L"  ~ Concentration / 1000,
      Units == "pg/mL" ~ Concentration / 1000,
      Units == "pg/ml" ~ Concentration / 1000,
      Units == "mg/L"  ~ Concentration * 1000,
      TRUE             ~ Concentration     # keep as is if no match
    )
  ) %>% 
  dplyr::filter(!is.na(Analyte_Code)) %>% 
  group_by(Study,Mat_PID,Analyte_Code) %>% 
  summarise(Concentration = mean(Concentration,na.rm = T)) %>% 
  mutate(across(everything(), ~ replace(., is.infinite(.), 0)))

myanalytes <- unique(Mat_Data_Targeted$Analyte_Code)

mat_analytes <- myanalytes

mat_list_Targeted <- list()
for(i in seq_along(myanalytes)){
  #print(i)
  curr_analyte <- myanalytes[i]
  mycols <- c("Mat_PID","Study",curr_analyte)
  
  curr_data <- Mat_Data_Targeted %>% 
    rownames_to_column("RN") %>% 
    dplyr::filter(Analyte_Code == curr_analyte) %>% 
    mutate(Study =  str_remove(Study, '[_]\\w+|:')) %>% 
    pivot_wider(names_from = Analyte_Code,values_from = Concentration) %>% 
    dplyr::select(all_of(mycols))
  
  mat_list_Targeted[[i]] <- curr_data
  names(mat_list_Targeted)[i] <- curr_analyte
  
}

```

```{r}
mypal <- paletteer_d("ggsci::springfield_simpsons")
mystudies  <- unique(ExWAS_SDOH_Exposures$State)
myanalytes <- unique(ZIP_Intervals$Outcome)
myanalytes <- c("TCP","DMP","DMTP","DEP")
```



Using State As Cohort Proxy
-------

```{r}
plot_data_list <- list()
interval_data_list <- list()


for(i in seq_along(myanalytes)){
  
  curr_analyte <- myanalytes[[i]]

  curr_interval <- ZIP_Intervals %>% 
    filter(Outcome == curr_analyte)

  curr_data <- mat_list_Targeted[[curr_analyte]] %>% 
      dplyr::filter(Study == "ZIP") %>% 
    mutate(Above_75 = ifelse(!!sym(curr_analyte) >= curr_interval$Tau75 * 2, 1, 0)) %>% 
    left_join(.,ExWAS_SDOH_Exposures,by = "Mat_PID") %>% 
    arrange(Country) %>% 
    rownames_to_column("ID") %>% 
    mutate(
     #plot_value = ifelse(Above_75 == 1, curr_interval$Tau75 * 2 + 1, !!sym(curr_analyte)),
      plot_value = !!sym(curr_analyte),
      ID = as.numeric(ID),
      curr_analyte = curr_analyte
    ) %>% 
    dplyr::filter(!is.na(Country))

  # Store the data only if there are less than 3 studies
 
    plot_data_list[[curr_analyte]] <- curr_data

    interval_data_list[[curr_analyte]] <- curr_interval %>%
      mutate(curr_analyte = curr_analyte)
  
}

# Combine all data into single dataframes
all_plot_data <- bind_rows(plot_data_list)
all_interval_data <- bind_rows(interval_data_list)

# Compute error_y and bar_height by analyte
error_df <- all_plot_data %>%
  group_by(curr_analyte) %>%
  summarise(
    error_y = mean(ID, na.rm = TRUE),
    bar_height = n() + 500,
    .groups = "drop"
  )

all_interval_data <- all_interval_data %>%
  left_join(error_df, by = "curr_analyte")

#mypal <- paletteer_d("ggsci::default_igv")
mypal <- paletteer_d("ggsci::springfield_simpsons")
label_log1p <- function(breaks) {
  label_number(
    accuracy = 0.1,
    trim = TRUE,
    scale_cut = cut_si("")   # e.g., 1k, 10k, 1M
  )(expm1(breaks))
}
site_colors <- c(
  "Nicaragua" = "#8A9197FF",
  "Guatemala"  = "#FED439FF",
  "Brazil"   = "#709AE1FF",
  "Puerto Rico"   = "#D2AF81FF"


)

# choose breaks on the log1p scale
x_breaks <- 0:7  # since you limit x to [0,7]
pdf(file = "../../../Output/Final_Paper1_Output/Plots/ZIP_Intervals.pdf",height = 6,width = 12)
zip_intervals <- ggplot() +
  # jittered observations
  geom_jitter(data = all_plot_data, aes(x = log1p(plot_value), y = Country, color = Country), size = 1.5, alpha = 0.5) +
  geom_point(data = all_interval_data, aes(y = 2.5, x = log1p(Tau50)), color = "#1A5354", size = 3) +
  geom_errorbarh(data = all_interval_data, aes(y = 2.5, xmin = log1p(Tau25), xmax = log1p(Tau75)), 
                 height = 4, color = "#1A5354", linewidth = 1) +
  geom_errorbarh(data = all_interval_data, aes(y = 2.5, xmin = log1p(Tau05), xmax = log1p(Tau95)), 
                 height = 4 / 2, color = "#1A5354", linewidth = 1, alpha = 0.6) +
  scale_color_manual(values = site_colors, guide = "legend", drop = FALSE) +
  scale_x_continuous(
    #limits = c(0, 7),
    breaks = x_breaks,
    labels = label_log1p(x_breaks),
    expand = expansion(mult = c(0.06, 0.02))
  ) +
 facet_wrap(~ curr_analyte, scales = "free_x", nrow = 1) +
  labs(
    title = "Exposure Intervals by Location in the ZIP Cohort",
    subtitle = "Points: observations (log1p scale). Dot: median (Tau50). Thick bar: IQR (Tau25–Tau75). Thin bar: 5–95%.",
    x = "Concentration (original scale)",
    y = NULL,
    color = "Location"
  ) +
  theme_classic(base_size = 12) +
  theme(
    plot.title = element_text(size = 20, face = "bold", hjust = 0),
    plot.subtitle = element_text(size = 12),
    strip.background = element_rect(fill = "#F2F2F2", color = NA),
    strip.text = element_text(size = 14, face = "bold"),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.4),
    panel.grid.minor = element_blank(),
    axis.title.x = element_text(size = 13, face = "bold"),
    axis.text.x = element_text(size = 8, face = "bold"),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.line.y = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    legend.box = "vertical",
    legend.key.height = unit(5, "mm"),
    legend.key.width  = unit(8, "mm"),
    panel.spacing = unit(10, "pt")
  ) +
  guides(
    color = guide_legend(
      nrow = 1,
      byrow = TRUE,
      override.aes = list(size = 3.2, alpha = 1)
    )
  ) +
  coord_cartesian(clip = "off")  # allow left-side labels to breathe
print(zip_intervals)
dev.off()

save(zip_intervals, file = "../../../Output/Final_Paper1_Output/zip_intervals.RData")
```



By SDOH
-----
```{r}
pdf(file = "../../../Output/Final_Paper1_Output/Plots/ZIP_SDOH_Intervals.pdf", height = 8, width = 8)

plots <- list()            # collect everything here
plot_idx <- 0
mystudies <- "ZIP"

for (i in seq_along(mystudies)) {

  # SDOH for this cohort
  curr_sdoh_data <- ExWAS_SDOH_Exposures %>%
    #dplyr::filter(Study == mystudies[[i]]) %>%
    dplyr::select(where(~ !all(is.na(.)))) %>%
    dplyr::select(where(~ dplyr::n_distinct(.) > 1)) %>% 
    dplyr::select(-Site_Location)

  # if Mat_PID is missing, skip (needed for joins)
  if (!"Mat_PID" %in% names(curr_sdoh_data)) next

  curr_demo_features <- names(curr_sdoh_data)[names(curr_sdoh_data) != "Mat_PID"]

    # Build long dataset of values for this study
    vals_list <- lapply(myanalytes, function(an) {
      df <- mat_list_Targeted[[an]] %>%
        dplyr::select(Mat_PID, !!sym(an))
      if (nrow(df) == 0) return(NULL)
      names(df)[names(df) == an] <- "Value"
      df$Outcome <- an
      df
    })
    
    ValuesLong <- vals_list %>%
      dplyr::bind_rows() %>%
      dplyr::filter(!is.na(Value))
    
    if (is.null(ValuesLong) || nrow(ValuesLong) == 0) next
    
    # ---- add this line: keep only analytes that appear in this study ----
    valid_outcomes <- unique(ValuesLong$Outcome)
    
    # Attach intervals only for those outcomes
    Intervals <- ZIP_Intervals %>%
      dplyr::filter(Outcome %in% valid_outcomes) %>%
      dplyr::select(Outcome, Tau05, Tau25, Tau50, Tau75, Tau95)
    
    # Merge and continue as before
    DF <- curr_sdoh_data %>%
      dplyr::left_join(ValuesLong, by = "Mat_PID") %>%
      dplyr::left_join(Intervals,  by = "Outcome") %>% 
      dplyr::filter(!is.na(Value))
    
    # Skip if there are no points for this study
    if (nrow(DF) == 0) next
    
    # ---- filter again to make sure each Outcome facet has ≥1 non-NA Value ----

    if (n_distinct(DF$Outcome) == 0) next

  # Guard: if nothing after join, skip
  if (nrow(DF) == 0) next

  for (j in seq_along(curr_demo_features)) {

    group_col <- curr_demo_features[[j]]

    # bucket age into quartiles if needed
    DF_plot <- DF
    if (group_col %in% c("Mat_Age", "Child_Age")) {
      DF_plot <- DF_plot %>%
        dplyr::mutate(quantile_group = as.factor(dplyr::ntile(!!sym(group_col), 4)))
      group_col <- "quantile_group"
    }

    # Drop missing group levels for this facetting run
    DF_plot <- DF_plot %>% dplyr::filter(!is.na(!!sym(group_col)))

    # If empty after filtering, skip
    if (nrow(DF_plot) == 0) next

    # Compute a common y-position for the interval bars across facets
    n_groups  <- length(unique(DF_plot[[group_col]]))
    error_y   <- (n_groups + 1) / 2
    bar_height <- n_groups

    # Intervals table with the y-position for geom_errorbarh/point; facets by Outcome automatically
    Intervals_y <- Intervals %>%
      dplyr::mutate(error_y = error_y, bar_height = bar_height) %>% 
      dplyr::filter(Outcome %in% DF_plot$Outcome)

    p <- ggplot() +
      geom_jitter(
        data = DF_plot,
        aes(x = log1p(Value), y = !!sym(group_col), color = !!sym(group_col)),
        size = 1.5, alpha = 1
      ) +
      scale_color_manual(values = mypal) +
      # 25–75
      geom_errorbarh(
        data = Intervals_y,
        aes(y = error_y, xmin = log1p(Tau25), xmax = log1p(Tau75)),
        inherit.aes = FALSE, height = bar_height, color = "#1A5354", linewidth = 1
      ) +
      # 5–95
      geom_errorbarh(
        data = Intervals_y,
        aes(y = error_y, xmin = log1p(Tau05), xmax = log1p(Tau95)),
        inherit.aes = FALSE, height = bar_height / 2, color = "#1A5354", linewidth = 1, alpha = 0.6
      ) +
      # median
      geom_point(
        data = Intervals_y,
        aes(y = error_y, x = log1p(Tau50)),
        inherit.aes = FALSE, color = "#1A5354", size = 6
      ) +
      facet_wrap(~ Outcome, scales = "free_x") +
      theme_classic() +
      labs(
        title = paste0("Exposure Quantiles : Cohort ", mystudies[[i]], " : ", curr_demo_features[j]),
        x = "log1p(Exposure)", y = curr_demo_features[[j]]
      )

    print(p)
    plot_idx <- plot_idx + 1
    key <- paste0(mystudies[[i]], "__", curr_demo_features[[j]])
    plots[[key]] <- p

  }
}

dev.off()
```
ZIP Map
-----
```{r}
coords <- tibble::tibble(
  Country = c("Guatemala", "Brazil", "Nicaragua", "Puerto Rico"),
  Latitude = c(15.7835, -14.2350, 12.8654, 18.2208),
  Longitude = c(-90.2308, -51.9253, -85.2072, -66.5901)
)


ZIP_Study_Locations <-ExWAS_SDOH_Exposures %>% 
  # mutate(
  #     Country = as.character(toupper(Country)),
  #     State   = as.character(toupper(State)),
  #     State   = dplyr::coalesce(State, Country)   # replace NA State with Country
  #   ) %>%
  group_by(Country) %>% 
  summarise(n = n()) %>% 
  dplyr::filter(!is.na(Country)) %>% 
  left_join(.,coords, by = "Country")

lat_long_df <-ZIP_Study_Locations 

my_sf <- lat_long_df %>% 
  st_as_sf(coords = c('Longitude', 'Latitude')) %>%
  st_set_crs(4326) # using 4326 for lat/lon decimal 

world <- ne_countries(scale = "medium", returnclass = "sf")

site_colors <- c(
  "Nicaragua" = "#8A9197FF",
  "Guatemala"  = "#FED439FF",
  "Brazil"   = "#709AE1FF",
  "Puerto Rico"   = "#D2AF81FF"


)

zip_map <- ggplot() +  
  geom_sf(data = world, fill = "lightyellow") +
  geom_sf(data = my_sf, size = 5, aes(color = Country,size = n)) +
  ggtitle("Map of ZIP Study Sites") + 
  coord_sf(
    xlim = c(-100, -40),   # longitude range (west to east)
    ylim = c(-30, 30),       # latitude range (south to north)
    expand = FALSE          # removes extra space around plot
  ) +
  scale_color_manual(values = site_colors) +
  theme_void() +
  theme(legend.position = "bottom"
)
save(zip_map,file =  "../../../Output/Final_Paper1_Output/zip_map.RData")
```



```{r}
r2_barplot_patch <- r2_barplot +
  theme(axis.text.y = element_text(size = 20,face = "bold"),
        axis.text.x = element_text(size = 20,face = "bold"),
        axis.title.x = element_text(size = 20,face = "bold"),
        axis.title.y = element_text(size = 20,face = "bold"))
design <- "
AB
CC
"

pdf(file = "../../../Output/Final_Paper1_Output/Plots/ZIP_Figure.pdf",height = 14,width =14)
patch_plot <- (zip_map + r2_barplot_patch)  / facet_zip_intervals 
patch_plot + plot_annotation(
  title = 'ZIP Study Analysis',
  tag_levels = "A"
) & 
  theme(plot.tag = element_text(size = 20),
        plot.title = element_text(size = 15))+
  plot_layout(design = design, widths = c(2, 1))
dev.off()

```

```{r}

```

